// This file is auto-generated by script/buildTypes.ts
// Emoji definition for AbButton
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f18e.png";

export const icon = png;
export const name = "AbButton";
export const aliases = ["ab_button","red-square","alphabet"];
export const width = 160;
export const height = 160;
export const unicode = "u1f18e";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
