// This file is auto-generated by script/buildTypes.ts
// Emoji definition for AButton
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f170.png";

export const icon = png;
export const name = "AButton";
export const aliases = ["a_button","red-square","alphabet","letter"];
export const width = 160;
export const height = 160;
export const unicode = "u1f170";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
