// This file is auto-generated by script/buildTypes.ts
// Emoji definition for AdmissionTickets
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f39f.png";

export const icon = png;
export const name = "AdmissionTickets";
export const aliases = ["admission tickets"];
export const width = 160;
export const height = 160;
export const unicode = "u1f39f";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
