// This file is auto-generated by script/buildTypes.ts
// Emoji definition for AlarmClock
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u23f0.png";

export const icon = png;
export const name = "AlarmClock";
export const aliases = ["alarm_clock","time","wake"];
export const width = 160;
export const height = 160;
export const unicode = "u23f0";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
