// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Ambulance
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f691.png";

export const icon = png;
export const name = "Ambulance";
export const aliases = ["ambulance","health","911","hospital"];
export const width = 160;
export const height = 160;
export const unicode = "u1f691";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
