// This file is auto-generated by script/buildTypes.ts
// Emoji definition for AmericanFootball
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f3c8.png";

export const icon = png;
export const name = "AmericanFootball";
export const aliases = ["american football","american_football","sports","balls","NFL"];
export const width = 160;
export const height = 160;
export const unicode = "u1f3c8";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
