// This file is auto-generated by script/buildTypes.ts
// Emoji definition for AnguishedFace
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f627.png";

export const icon = png;
export const name = "AnguishedFace";
export const aliases = ["anguished face","anguished_face","face","stunned","nervous"];
export const width = 160;
export const height = 160;
export const unicode = "u1f627";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
