// This file is auto-generated by script/buildTypes.ts
// Emoji definition for BabyAngelDarkSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f47c_1f3ff.png";

export const icon = png;
export const name = "BabyAngelDarkSkinTone";
export const aliases = ["baby angel: dark skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1f47c_1f3ff";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
