// This file is auto-generated by script/buildTypes.ts
// Emoji definition for BackhandIndexPointingDown
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f447.png";

export const icon = png;
export const name = "BackhandIndexPointingDown";
export const aliases = ["backhand index pointing down","backhand_index_pointing_down","fingers","hand","direction","down"];
export const width = 160;
export const height = 160;
export const unicode = "u1f447";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
