// This file is auto-generated by script/buildTypes.ts
// Emoji definition for BackhandIndexPointingUp
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f446.png";

export const icon = png;
export const name = "BackhandIndexPointingUp";
export const aliases = ["backhand index pointing up","backhand_index_pointing_up","fingers","hand","direction","up"];
export const width = 160;
export const height = 160;
export const unicode = "u1f446";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
