// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Basketball
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f3c0.png";

export const icon = png;
export const name = "Basketball";
export const aliases = ["basketball","basketball","sports","balls","NBA"];
export const width = 160;
export const height = 160;
export const unicode = "u1f3c0";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
