// This file is auto-generated by script/buildTypes.ts
// Emoji definition for BButton
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f171.png";

export const icon = png;
export const name = "BButton";
export const aliases = ["b_button","red-square","alphabet","letter"];
export const width = 160;
export const height = 160;
export const unicode = "u1f171";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
