// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Beans
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1fad8.png";

export const icon = png;
export const name = "Beans";
export const aliases = ["beans","food"];
export const width = 160;
export const height = 160;
export const unicode = "u1fad8";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
