// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Bell
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f514.png";

export const icon = png;
export const name = "Bell";
export const aliases = ["bell","bell","sound","notification","christmas","xmas","chime"];
export const width = 160;
export const height = 160;
export const unicode = "u1f514";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
