// This file is auto-generated by script/buildTypes.ts
// Emoji definition for BilledCap
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f9e2.png";

export const icon = png;
export const name = "BilledCap";
export const aliases = ["billed cap","billed_cap","cap","baseball"];
export const width = 160;
export const height = 160;
export const unicode = "u1f9e2";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
