// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Biohazard
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u2623.png";

export const icon = png;
export const name = "Biohazard";
export const aliases = ["biohazard","danger"];
export const width = 160;
export const height = 160;
export const unicode = "u2623";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
