// This file is auto-generated by script/buildTypes.ts
// Emoji definition for BitingLip
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1fae6.png";

export const icon = png;
export const name = "BitingLip";
export const aliases = ["biting lip","biting lip","flirt","sexy","pain","worry"];
export const width = 160;
export const height = 160;
export const unicode = "u1fae6";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
