// This file is auto-generated by script/buildTypes.ts
// Emoji definition for BlackSmallSquare
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u25aa.png";

export const icon = png;
export const name = "BlackSmallSquare";
export const aliases = ["black_small_square","shape","icon"];
export const width = 160;
export const height = 160;
export const unicode = "u25aa";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
