// This file is auto-generated by script/buildTypes.ts
// Emoji definition for BlackMediumSmallSquare
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u25fe.png";

export const icon = png;
export const name = "BlackMediumSmallSquare";
export const aliases = ["black_medium_small_square","icon","shape","button"];
export const width = 160;
export const height = 160;
export const unicode = "u25fe";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
