// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Books
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f4da.png";

export const icon = png;
export const name = "Books";
export const aliases = ["books","books","literature","library","study"];
export const width = 160;
export const height = 160;
export const unicode = "u1f4da";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
