// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Boy
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f466.png";

export const icon = png;
export const name = "Boy";
export const aliases = ["boy","boy","man","male","guy","teenager"];
export const width = 160;
export const height = 160;
export const unicode = "u1f466";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
