// This file is auto-generated by script/buildTypes.ts
// Emoji definition for BottleWithPoppingCork
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f37e.png";

export const icon = png;
export const name = "BottleWithPoppingCork";
export const aliases = ["bottle_with_popping_cork","drink","wine","bottle","celebration"];
export const width = 160;
export const height = 160;
export const unicode = "u1f37e";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
