// This file is auto-generated by script/buildTypes.ts
// Emoji definition for BrownHeart
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f90e.png";

export const icon = png;
export const name = "BrownHeart";
export const aliases = ["brown_heart","coffee"];
export const width = 160;
export const height = 160;
export const unicode = "u1f90e";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
