// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Bread
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f35e.png";

export const icon = png;
export const name = "Bread";
export const aliases = ["bread","bread","food","wheat","breakfast","toast"];
export const width = 160;
export const height = 160;
export const unicode = "u1f35e";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
