// This file is auto-generated by script/buildTypes.ts
// Emoji definition for BrokenHeart
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f494.png";

export const icon = png;
export const name = "BrokenHeart";
export const aliases = ["broken heart","broken_heart","sad","sorry","break","heart","heartbreak"];
export const width = 160;
export const height = 160;
export const unicode = "u1f494";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
