// This file is auto-generated by script/buildTypes.ts
// Emoji definition for BubbleTea
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f9cb.png";

export const icon = png;
export const name = "BubbleTea";
export const aliases = ["bubble tea","taiwan","boba","milk tea","straw"];
export const width = 160;
export const height = 160;
export const unicode = "u1f9cb";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
