// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Burrito
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f32f.png";

export const icon = png;
export const name = "Burrito";
export const aliases = ["burrito","food","mexican"];
export const width = 160;
export const height = 160;
export const unicode = "u1f32f";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
