// This file is auto-generated by script/buildTypes.ts
// Emoji definition for CarouselHorse
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f3a0.png";

export const icon = png;
export const name = "CarouselHorse";
export const aliases = ["carousel horse","carousel_horse","photo","carnival"];
export const width = 160;
export const height = 160;
export const unicode = "u1f3a0";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
