// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Canoe
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f6f6.png";

export const icon = png;
export const name = "Canoe";
export const aliases = ["canoe","boat","paddle","water","ship"];
export const width = 160;
export const height = 160;
export const unicode = "u1f6f6";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
