// This file is auto-generated by script/buildTypes.ts
// Emoji definition for CarpStreamer
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f38f.png";

export const icon = png;
export const name = "CarpStreamer";
export const aliases = ["carp_streamer","fish","japanese","koinobori","carp","banner"];
export const width = 160;
export const height = 160;
export const unicode = "u1f38f";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
