// This file is auto-generated by script/buildTypes.ts
// Emoji definition for CannedFood
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f96b.png";

export const icon = png;
export const name = "CannedFood";
export const aliases = ["canned food","canned_food","food","soup","tomatoes"];
export const width = 160;
export const height = 160;
export const unicode = "u1f96b";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
