// This file is auto-generated by script/buildTypes.ts
// Emoji definition for CarpentrySaw
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1fa9a.png";

export const icon = png;
export const name = "CarpentrySaw";
export const aliases = ["carpentry saw","carpentry saw","cut","chop"];
export const width = 160;
export const height = 160;
export const unicode = "u1fa9a";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
