// This file is auto-generated by script/buildTypes.ts
// Emoji definition for CardFileBox
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f5c3.png";

export const icon = png;
export const name = "CardFileBox";
export const aliases = ["card file box"];
export const width = 160;
export const height = 160;
export const unicode = "u1f5c3";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
