// This file is auto-generated by script/buildTypes.ts
// Emoji definition for CallMeHandLightSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f919_1f3fb.png";

export const icon = png;
export const name = "CallMeHandLightSkinTone";
export const aliases = ["call me hand: light skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1f919_1f3fb";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
