// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ChartDecreasing
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f4c9.png";

export const icon = png;
export const name = "ChartDecreasing";
export const aliases = ["chart decreasing","chart_decreasing","graph","presentation","stats","recession","business","economics","money","sales","bad","failure"];
export const width = 160;
export const height = 160;
export const unicode = "u1f4c9";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
