// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Chicken
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f414.png";

export const icon = png;
export const name = "Chicken";
export const aliases = ["chicken","chicken","animal","cluck","nature","bird"];
export const width = 160;
export const height = 160;
export const unicode = "u1f414";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
