// This file is auto-generated by script/buildTypes.ts
// Emoji definition for CheckMarkButton
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u2705.png";

export const icon = png;
export const name = "CheckMarkButton";
export const aliases = ["check_mark_button","green-square","ok","agree","vote","election","answer","tick"];
export const width = 160;
export const height = 160;
export const unicode = "u2705";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
