// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Chestnut
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f330.png";

export const icon = png;
export const name = "Chestnut";
export const aliases = ["chestnut","chestnut","food","squirrel"];
export const width = 160;
export const height = 160;
export const unicode = "u1f330";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
