// This file is auto-generated by script/buildTypes.ts
// Emoji definition for CheckBoxWithCheck
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u2611.png";

export const icon = png;
export const name = "CheckBoxWithCheck";
export const aliases = ["check box with check"];
export const width = 160;
export const height = 160;
export const unicode = "u2611";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
