// This file is auto-generated by script/buildTypes.ts
// Emoji definition for CityscapeAtDusk
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f306.png";

export const icon = png;
export const name = "CityscapeAtDusk";
export const aliases = ["cityscape at dusk","cityscape_at_dusk","photo","evening","sky","buildings"];
export const width = 160;
export const height = 160;
export const unicode = "u1f306";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
