// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ClubSuit
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u2663.png";

export const icon = png;
export const name = "ClubSuit";
export const aliases = ["club_suit","poker","cards","magic","suits"];
export const width = 160;
export const height = 160;
export const unicode = "u2663";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
