// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ClutchBag
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f45d.png";

export const icon = png;
export const name = "ClutchBag";
export const aliases = ["clutch bag","clutch_bag","bag","accessories","shopping"];
export const width = 160;
export const height = 160;
export const unicode = "u1f45d";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
