// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ClosedMailboxWithRaisedFlag
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f4eb.png";

export const icon = png;
export const name = "ClosedMailboxWithRaisedFlag";
export const aliases = ["closed mailbox with raised flag","closed_mailbox_with_raised_flag","email","inbox","communication"];
export const width = 160;
export const height = 160;
export const unicode = "u1f4eb";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
