// This file is auto-generated by script/buildTypes.ts
// Emoji definition for CloudWithLightningAndRain
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u26c8.png";

export const icon = png;
export const name = "CloudWithLightningAndRain";
export const aliases = ["cloud with lightning and rain"];
export const width = 160;
export const height = 160;
export const unicode = "u26c8";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
