// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Clamp
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f5dc.png";

export const icon = png;
export const name = "Clamp";
export const aliases = ["clamp"];
export const width = 160;
export const height = 160;
export const unicode = "u1f5dc";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
