// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Cooking
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f373.png";

export const icon = png;
export const name = "Cooking";
export const aliases = ["cooking","food","breakfast","kitchen","egg","skillet"];
export const width = 160;
export const height = 160;
export const unicode = "u1f373";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
