// This file is auto-generated by script/buildTypes.ts
// Emoji definition for CoupleWithHeartWomanMan
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f469.png";

export const icon = png;
export const name = "CoupleWithHeartWomanMan";
export const aliases = ["couple_with_heart_woman_man","love"];
export const width = 160;
export const height = 160;
export const unicode = "u1f469";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
