// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Coin
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1fa99.png";

export const icon = png;
export const name = "Coin";
export const aliases = ["coin","coin","money","currency"];
export const width = 160;
export const height = 160;
export const unicode = "u1fa99";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
