// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Cookie
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f36a.png";

export const icon = png;
export const name = "Cookie";
export const aliases = ["cookie","cookie","food","snack","oreo","chocolate","sweet","dessert"];
export const width = 160;
export const height = 160;
export const unicode = "u1f36a";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
