// This file is auto-generated by script/buildTypes.ts
// Emoji definition for CoupleWithHeartWomanWomanMediumLightSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f469_1f3fc_200d_2764_fe0f_200d_1f469_1f3fc.png";

export const icon = png;
export const name = "CoupleWithHeartWomanWomanMediumLightSkinTone";
export const aliases = ["couple with heart: woman, woman, medium-light skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1f469_1f3fc_200d_2764_fe0f_200d_1f469_1f3fc";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
