// This file is auto-generated by script/buildTypes.ts
// Emoji definition for CookDarkSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f9d1_1f3ff_200d_1f373.png";

export const icon = png;
export const name = "CookDarkSkinTone";
export const aliases = ["cook: dark skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1f9d1_1f3ff_200d_1f373";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
