// This file is auto-generated by script/buildTypes.ts
// Emoji definition for CoupleWithHeartManManLightSkinToneMediumDarkSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f468_1f3fb_200d_2764_fe0f_200d_1f468_1f3fe.png";

export const icon = png;
export const name = "CoupleWithHeartManManLightSkinToneMediumDarkSkinTone";
export const aliases = ["couple with heart: man, man, light skin tone, medium-dark skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1f468_1f3fb_200d_2764_fe0f_200d_1f468_1f3fe";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
