// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ConfoundedFace
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f616.png";

export const icon = png;
export const name = "ConfoundedFace";
export const aliases = ["confounded_face","face","confused","sick","unwell","oops",":S"];
export const width = 160;
export const height = 160;
export const unicode = "u1f616";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
