// This file is auto-generated by script/buildTypes.ts
// Emoji definition for COOLButton
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f192.png";

export const icon = png;
export const name = "COOLButton";
export const aliases = ["COOL button","cool_button","words","blue-square"];
export const width = 160;
export const height = 160;
export const unicode = "u1f192";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
