// This file is auto-generated by script/buildTypes.ts
// Emoji definition for CoupleWithHeartWomanManDarkSkinToneLightSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f469_1f3ff_200d_2764_fe0f_200d_1f468_1f3fb.png";

export const icon = png;
export const name = "CoupleWithHeartWomanManDarkSkinToneLightSkinTone";
export const aliases = ["couple with heart: woman, man, dark skin tone, light skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1f469_1f3ff_200d_2764_fe0f_200d_1f468_1f3fb";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
