// This file is auto-generated by script/buildTypes.ts
// Emoji definition for CounterclockwiseArrowsButton
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f504.png";

export const icon = png;
export const name = "CounterclockwiseArrowsButton";
export const aliases = ["counterclockwise_arrows_button","blue-square","sync","cycle"];
export const width = 160;
export const height = 160;
export const unicode = "u1f504";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
