// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Construction
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f6a7.png";

export const icon = png;
export const name = "Construction";
export const aliases = ["construction","wip","progress","caution","warning"];
export const width = 160;
export const height = 160;
export const unicode = "u1f6a7";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
