// This file is auto-generated by script/buildTypes.ts
// Emoji definition for CryingFace
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f622.png";

export const icon = png;
export const name = "CryingFace";
export const aliases = ["crying face","crying_face","face","tears","sad","depressed","upset",":'("];
export const width = 160;
export const height = 160;
export const unicode = "u1f622";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
