// This file is auto-generated by script/buildTypes.ts
// Emoji definition for CryingCat
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f63f.png";

export const icon = png;
export const name = "CryingCat";
export const aliases = ["crying_cat","animal","tears","weep","sad","cats","upset","cry"];
export const width = 160;
export const height = 160;
export const unicode = "u1f63f";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
