// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Crutch
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1fa7c.png";

export const icon = png;
export const name = "Crutch";
export const aliases = ["crutch","crutch","accessibility","assist"];
export const width = 160;
export const height = 160;
export const unicode = "u1fa7c";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
