// This file is auto-generated by script/buildTypes.ts
// Emoji definition for DeafWoman
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f9cf.png";

export const icon = png;
export const name = "DeafWoman";
export const aliases = ["deaf_woman","accessibility"];
export const width = 160;
export const height = 160;
export const unicode = "u1f9cf";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
