// This file is auto-generated by script/buildTypes.ts
// Emoji definition for DirectHit
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f3af.png";

export const icon = png;
export const name = "DirectHit";
export const aliases = ["direct_hit","game","play","bar","target","bullseye"];
export const width = 160;
export const height = 160;
export const unicode = "u1f3af";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
