// This file is auto-generated by script/buildTypes.ts
// Emoji definition for DiamondWithADot
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f4a0.png";

export const icon = png;
export const name = "DiamondWithADot";
export const aliases = ["diamond with a dot","diamond_with_a_dot","jewel","blue","gem","crystal","fancy"];
export const width = 160;
export const height = 160;
export const unicode = "u1f4a0";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
