// This file is auto-generated by script/buildTypes.ts
// Emoji definition for DiyaLamp
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1fa94.png";

export const icon = png;
export const name = "DiyaLamp";
export const aliases = ["diya lamp","diya_lamp","lighting"];
export const width = 160;
export const height = 160;
export const unicode = "u1fa94";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
