// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Dna
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f9ec.png";

export const icon = png;
export const name = "Dna";
export const aliases = ["dna","biologist","genetics","life"];
export const width = 160;
export const height = 160;
export const unicode = "u1f9ec";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
