// This file is auto-generated by script/buildTypes.ts
// Emoji definition for DottedSixPointedStar
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f52f.png";

export const icon = png;
export const name = "DottedSixPointedStar";
export const aliases = ["dotted_six_pointed_star","purple-square","religion","jewish","hexagram"];
export const width = 160;
export const height = 160;
export const unicode = "u1f52f";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
