// This file is auto-generated by script/buildTypes.ts
// Emoji definition for DownLeftArrow
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u2199.png";

export const icon = png;
export const name = "DownLeftArrow";
export const aliases = ["down_left_arrow","blue-square","direction","diagonal","southwest"];
export const width = 160;
export const height = 160;
export const unicode = "u2199";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
