// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Doughnut
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f369.png";

export const icon = png;
export const name = "Doughnut";
export const aliases = ["doughnut","food","dessert","snack","sweet","donut"];
export const width = 160;
export const height = 160;
export const unicode = "u1f369";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
