// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Dodo
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f9a4.png";

export const icon = png;
export const name = "Dodo";
export const aliases = ["dodo","dodo","animal","bird"];
export const width = 160;
export const height = 160;
export const unicode = "u1f9a4";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
