// This file is auto-generated by script/buildTypes.ts
// Emoji definition for DogFace
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f436.png";

export const icon = png;
export const name = "DogFace";
export const aliases = ["dog face","dog_face","animal","friend","nature","woof","puppy","pet","faithful"];
export const width = 160;
export const height = 160;
export const unicode = "u1f436";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
