// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Ear
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f442.png";

export const icon = png;
export const name = "Ear";
export const aliases = ["ear","face","hear","sound","listen"];
export const width = 160;
export const height = 160;
export const unicode = "u1f442";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
