// This file is auto-generated by script/buildTypes.ts
// Emoji definition for EjectButton
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u23cf.png";

export const icon = png;
export const name = "EjectButton";
export const aliases = ["eject button"];
export const width = 160;
export const height = 160;
export const unicode = "u23cf";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
