// This file is auto-generated by script/buildTypes.ts
// Emoji definition for EMail
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f4e7.png";

export const icon = png;
export const name = "EMail";
export const aliases = ["e-mail","e_mail","communication","inbox"];
export const width = 160;
export const height = 160;
export const unicode = "u1f4e7";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
