// This file is auto-generated by script/buildTypes.ts
// Emoji definition for EnvelopeWithArrow
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f4e9.png";

export const icon = png;
export const name = "EnvelopeWithArrow";
export const aliases = ["envelope with arrow","envelope_with_arrow","email","communication"];
export const width = 160;
export const height = 160;
export const unicode = "u1f4e9";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
