// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ExclamationQuestionMark
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u2049.png";

export const icon = png;
export const name = "ExclamationQuestionMark";
export const aliases = ["exclamation question mark"];
export const width = 160;
export const height = 160;
export const unicode = "u2049";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
