// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Eyes
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f440.png";

export const icon = png;
export const name = "Eyes";
export const aliases = ["eyes","eyes","look","watch","stalk","peek","see"];
export const width = 160;
export const height = 160;
export const unicode = "u1f440";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
