// This file is auto-generated by script/buildTypes.ts
// Emoji definition for EyeInSpeechBubble
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f441.png";

export const icon = png;
export const name = "EyeInSpeechBubble";
export const aliases = ["eye_in_speech_bubble","info"];
export const width = 160;
export const height = 160;
export const unicode = "u1f441";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
