// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FaceWithSpiralEyes
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f635_200d_1f4ab.png";

export const icon = png;
export const name = "FaceWithSpiralEyes";
export const aliases = ["face with spiral eyes","face with spiral eyes","sick","ill","confused","nauseous","nausea"];
export const width = 160;
export const height = 160;
export const unicode = "u1f635_200d_1f4ab";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
