// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FamilyManGirlBoy
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f468_200d_1f467_200d_1f466.png";

export const icon = png;
export const name = "FamilyManGirlBoy";
export const aliases = ["family: man, girl, boy","family_man_girl_boy","home","parent","people","human","children"];
export const width = 160;
export const height = 160;
export const unicode = "u1f468_200d_1f467_200d_1f466";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
