// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FastReverseButton
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u23ea.png";

export const icon = png;
export const name = "FastReverseButton";
export const aliases = ["fast_reverse_button","play","blue-square"];
export const width = 160;
export const height = 160;
export const unicode = "u23ea";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
