// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FamilyManWomanGirlBoy
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f468.png";

export const icon = png;
export const name = "FamilyManWomanGirlBoy";
export const aliases = ["family_man_woman_girl_boy","home","parents","people","human","children"];
export const width = 160;
export const height = 160;
export const unicode = "u1f468";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
