// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FaceWithRollingEyes
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f644.png";

export const icon = png;
export const name = "FaceWithRollingEyes";
export const aliases = ["face_with_rolling_eyes","face","eyeroll","frustrated"];
export const width = 160;
export const height = 160;
export const unicode = "u1f644";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
