// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FaceWithTongue
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f61b.png";

export const icon = png;
export const name = "FaceWithTongue";
export const aliases = ["face_with_tongue","face","prank","childish","playful","mischievous","smile","tongue"];
export const width = 160;
export const height = 160;
export const unicode = "u1f61b";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
