// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FaceInClouds
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f636.png";

export const icon = png;
export const name = "FaceInClouds";
export const aliases = ["face in clouds","shower","steam","dream"];
export const width = 160;
export const height = 160;
export const unicode = "u1f636";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
