// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FaceExhaling
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f62e.png";

export const icon = png;
export const name = "FaceExhaling";
export const aliases = ["face exhaling","relieve","relief","tired","sigh"];
export const width = 160;
export const height = 160;
export const unicode = "u1f62e";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
