// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FamilyWomanWomanBoyBoy
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f469.png";

export const icon = png;
export const name = "FamilyWomanWomanBoyBoy";
export const aliases = ["family_woman_woman_boy_boy","home","parents","people","human","children"];
export const width = 160;
export const height = 160;
export const unicode = "u1f469";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
