// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FamilyManManGirl
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f468_200d_1f468_200d_1f467.png";

export const icon = png;
export const name = "FamilyManManGirl";
export const aliases = ["family: man, man, girl","family_man_man_girl","home","parents","people","human","children"];
export const width = 160;
export const height = 160;
export const unicode = "u1f468_200d_1f468_200d_1f467";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
