// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FaceHoldingBackTears
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f979.png";

export const icon = png;
export const name = "FaceHoldingBackTears";
export const aliases = ["face holding back tears","face holding back tears","touched","gratitude","cry"];
export const width = 160;
export const height = 160;
export const unicode = "u1f979";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
