// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FemaleSign
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u2640.png";

export const icon = png;
export const name = "FemaleSign";
export const aliases = ["female_sign","woman","women","lady","girl"];
export const width = 160;
export const height = 160;
export const unicode = "u2640";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
