// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FilmFrames
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f39e.png";

export const icon = png;
export const name = "FilmFrames";
export const aliases = ["film frames"];
export const width = 160;
export const height = 160;
export const unicode = "u1f39e";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
