// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Fireworks
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f386.png";

export const icon = png;
export const name = "Fireworks";
export const aliases = ["fireworks","photo","festival","carnival","congratulations"];
export const width = 160;
export const height = 160;
export const unicode = "u1f386";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
