// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagBangladesh
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1e7_1f1e9.png";

export const icon = png;
export const name = "FlagBangladesh";
export const aliases = ["flag: Bangladesh","flag_bangladesh","bd","flag","nation","country","banner","bangladesh"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1e7_1f1e9";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
