// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FleurDeLis
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u269c.png";

export const icon = png;
export const name = "FleurDeLis";
export const aliases = ["fleur_de_lis","decorative","scout"];
export const width = 160;
export const height = 160;
export const unicode = "u269c";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
