// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagStKittsNevis
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1f0_1f1f3.png";

export const icon = png;
export const name = "FlagStKittsNevis";
export const aliases = ["flag: St. Kitts & Nevis","flag_st_kitts_nevis","saint","kitts","nevis","flag","nation","country","banner","st_kitts_nevis"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1f0_1f1f3";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
