// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagScotland
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f3f4_e0067_e0062_e0073_e0063_e0074_e007f.png";

export const icon = png;
export const name = "FlagScotland";
export const aliases = ["flag: Scotland","flag_scotland","flag","scottish"];
export const width = 160;
export const height = 160;
export const unicode = "u1f3f4_e0067_e0062_e0073_e0063_e0074_e007f";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
