// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagMicronesia
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1eb_1f1f2.png";

export const icon = png;
export const name = "FlagMicronesia";
export const aliases = ["flag: Micronesia","flag_micronesia","micronesia","federated","states","flag","nation","country","banner","micronesia"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1eb_1f1f2";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
