// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagCuba
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1e8.png";

export const icon = png;
export const name = "FlagCuba";
export const aliases = ["flag_cuba","cu","flag","nation","country","banner","cuba"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1e8";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
