// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagCongoBrazzaville
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1e8_1f1ec.png";

export const icon = png;
export const name = "FlagCongoBrazzaville";
export const aliases = ["flag: Congo - Brazzaville","flag_congo_brazzaville","congo","flag","nation","country","banner","congo_brazzaville"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1e8_1f1ec";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
