// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagTimorLeste
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1f9_1f1f1.png";

export const icon = png;
export const name = "FlagTimorLeste";
export const aliases = ["flag: Timor-Leste","flag_timor_leste","timor","leste","flag","nation","country","banner","timor_leste"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1f9_1f1f1";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
