// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagMali
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1f2_1f1f1.png";

export const icon = png;
export const name = "FlagMali";
export const aliases = ["flag: Mali","flag_mali","ml","flag","nation","country","banner","mali"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1f2_1f1f1";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
