// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Flashlight
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f526.png";

export const icon = png;
export const name = "Flashlight";
export const aliases = ["flashlight","dark","camping","sight","night"];
export const width = 160;
export const height = 160;
export const unicode = "u1f526";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
