// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagRussia
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1f7_1f1fa.png";

export const icon = png;
export const name = "FlagRussia";
export const aliases = ["flag: Russia","flag_russia","russian","federation","flag","nation","country","banner","russia"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1f7_1f1fa";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
