// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagSuriname
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1f8.png";

export const icon = png;
export const name = "FlagSuriname";
export const aliases = ["flag_suriname","sr","flag","nation","country","banner","suriname"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1f8";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
