// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagCambodia
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1f0_1f1ed.png";

export const icon = png;
export const name = "FlagCambodia";
export const aliases = ["flag: Cambodia","flag_cambodia","kh","flag","nation","country","banner","cambodia"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1f0_1f1ed";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
