// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlexedBicepsMediumSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f4aa_1f3fd.png";

export const icon = png;
export const name = "FlexedBicepsMediumSkinTone";
export const aliases = ["flexed biceps: medium skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1f4aa_1f3fd";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
