// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagStLucia
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1f1_1f1e8.png";

export const icon = png;
export const name = "FlagStLucia";
export const aliases = ["flag: St. Lucia","flag_st_lucia","saint","lucia","flag","nation","country","banner","st_lucia"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1f1_1f1e8";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
