// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagUzbekistan
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1fa.png";

export const icon = png;
export const name = "FlagUzbekistan";
export const aliases = ["flag_uzbekistan","uz","flag","nation","country","banner","uzbekistan"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1fa";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
