// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagKiribati
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1f0.png";

export const icon = png;
export const name = "FlagKiribati";
export const aliases = ["flag_kiribati","ki","flag","nation","country","banner","kiribati"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1f0";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
