// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagLesotho
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1f1.png";

export const icon = png;
export const name = "FlagLesotho";
export const aliases = ["flag_lesotho","ls","flag","nation","country","banner","lesotho"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1f1";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
