// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagTunisia
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1f9_1f1f3.png";

export const icon = png;
export const name = "FlagTunisia";
export const aliases = ["flag: Tunisia","flag_tunisia","tn","flag","nation","country","banner","tunisia"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1f9_1f1f3";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
