// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagSouthAfrica
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1ff.png";

export const icon = png;
export const name = "FlagSouthAfrica";
export const aliases = ["flag_south_africa","south","africa","flag","nation","country","banner","south_africa"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1ff";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
