// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagChristmasIsland
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1e8_1f1fd.png";

export const icon = png;
export const name = "FlagChristmasIsland";
export const aliases = ["flag: Christmas Island","flag_christmas_island","christmas","island","flag","nation","country","banner","christmas_island"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1e8_1f1fd";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
