// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagBelarus
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1e7_1f1fe.png";

export const icon = png;
export const name = "FlagBelarus";
export const aliases = ["flag: Belarus","flag_belarus","by","flag","nation","country","banner","belarus"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1e7_1f1fe";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
