// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagInHole
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u26f3.png";

export const icon = png;
export const name = "FlagInHole";
export const aliases = ["flag_in_hole","sports","business","flag","hole","summer"];
export const width = 160;
export const height = 160;
export const unicode = "u26f3";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
