// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagCanaryIslands
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1ee.png";

export const icon = png;
export const name = "FlagCanaryIslands";
export const aliases = ["flag_canary_islands","canary","islands","flag","nation","country","banner","canary_islands"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1ee";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
