// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagBrunei
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1e7.png";

export const icon = png;
export const name = "FlagBrunei";
export const aliases = ["flag_brunei","bn","darussalam","flag","nation","country","banner","brunei"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1e7";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
