// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagElSalvador
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1f8_1f1fb.png";

export const icon = png;
export const name = "FlagElSalvador";
export const aliases = ["flag: El Salvador","flag_el_salvador","el","salvador","flag","nation","country","banner","el_salvador"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1f8_1f1fb";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
