// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagKazakhstan
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1f0.png";

export const icon = png;
export const name = "FlagKazakhstan";
export const aliases = ["flag_kazakhstan","kz","flag","nation","country","banner","kazakhstan"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1f0";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
