// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagTanzania
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1f9_1f1ff.png";

export const icon = png;
export const name = "FlagTanzania";
export const aliases = ["flag: Tanzania","flag_tanzania","tanzania","united","republic","flag","nation","country","banner","tanzania"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1f9_1f1ff";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
