// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagJapan
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1ef_1f1f5.png";

export const icon = png;
export const name = "FlagJapan";
export const aliases = ["flag: Japan","flag_japan","japanese","nation","flag","country","banner","japan","jp","ja"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1ef_1f1f5";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
