// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagItaly
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1ee.png";

export const icon = png;
export const name = "FlagItaly";
export const aliases = ["flag_italy","italy","flag","nation","country","banner","italy"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1ee";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
