// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagTajikistan
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1f9_1f1ef.png";

export const icon = png;
export const name = "FlagTajikistan";
export const aliases = ["flag: Tajikistan","flag_tajikistan","tj","flag","nation","country","banner","tajikistan"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1f9_1f1ef";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
