// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagGuyana
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1ec_1f1fe.png";

export const icon = png;
export const name = "FlagGuyana";
export const aliases = ["flag: Guyana","flag_guyana","gy","flag","nation","country","banner","guyana"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1ec_1f1fe";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
