// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagUnitedArabEmirates
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1e6_1f1ea.png";

export const icon = png;
export const name = "FlagUnitedArabEmirates";
export const aliases = ["flag: United Arab Emirates","flag_united_arab_emirates","united","arab","emirates","flag","nation","country","banner","united_arab_emirates"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1e6_1f1ea";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
