// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagSintMaarten
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1f8.png";

export const icon = png;
export const name = "FlagSintMaarten";
export const aliases = ["flag_sint_maarten","sint","maarten","dutch","flag","nation","country","banner","sint_maarten"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1f8";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
