// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagSouthKorea
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1f0_1f1f7.png";

export const icon = png;
export const name = "FlagSouthKorea";
export const aliases = ["flag: South Korea","flag_south_korea","south","korea","nation","flag","country","banner","south_korea"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1f0_1f1f7";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
