// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagSvalbardJanMayen
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1f8_1f1ef.png";

export const icon = png;
export const name = "FlagSvalbardJanMayen";
export const aliases = ["flag: Svalbard & Jan Mayen","flag_svalbard_jan_mayen"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1f8_1f1ef";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
