// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagEritrea
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1ea.png";

export const icon = png;
export const name = "FlagEritrea";
export const aliases = ["flag_eritrea","er","flag","nation","country","banner","eritrea"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1ea";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
