// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagMacaoSarChina
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1f2.png";

export const icon = png;
export const name = "FlagMacaoSarChina";
export const aliases = ["flag_macao_sar_china","macao","flag","nation","country","banner","macao_sar_china"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1f2";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
