// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlatShoe
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f97f.png";

export const icon = png;
export const name = "FlatShoe";
export const aliases = ["flat_shoe","ballet","slip-on","slipper"];
export const width = 160;
export const height = 160;
export const unicode = "u1f97f";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
