// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagPanama
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1f5_1f1e6.png";

export const icon = png;
export const name = "FlagPanama";
export const aliases = ["flag: Panama","flag_panama","pa","flag","nation","country","banner","panama"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1f5_1f1e6";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
