// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagHonduras
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1ed.png";

export const icon = png;
export const name = "FlagHonduras";
export const aliases = ["flag_honduras","hn","flag","nation","country","banner","honduras"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1ed";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
