// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagGambia
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1ec_1f1f2.png";

export const icon = png;
export const name = "FlagGambia";
export const aliases = ["flag: Gambia","flag_gambia","gm","flag","nation","country","banner","gambia"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1ec_1f1f2";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
