// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagBouvetIsland
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1e7_1f1fb.png";

export const icon = png;
export const name = "FlagBouvetIsland";
export const aliases = ["flag: Bouvet Island","flag_bouvet_island","norway"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1e7_1f1fb";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
