// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagMalta
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1f2_1f1f9.png";

export const icon = png;
export const name = "FlagMalta";
export const aliases = ["flag: Malta","flag_malta","mt","flag","nation","country","banner","malta"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1f2_1f1f9";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
