// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagStBarthelemy
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1e7_1f1f1.png";

export const icon = png;
export const name = "FlagStBarthelemy";
export const aliases = ["flag: St. Barthelemy","flag_st_barthelemy","saint","barthélemy","flag","nation","country","banner","st_barthelemy"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1e7_1f1f1";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
