// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagIraq
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1ee.png";

export const icon = png;
export const name = "FlagIraq";
export const aliases = ["flag_iraq","iq","flag","nation","country","banner","iraq"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1ee";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
