// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagCyprus
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1e8_1f1fe.png";

export const icon = png;
export const name = "FlagCyprus";
export const aliases = ["flag: Cyprus","flag_cyprus","cy","flag","nation","country","banner","cyprus"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1e8_1f1fe";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
