// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagSyria
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1f8_1f1fe.png";

export const icon = png;
export const name = "FlagSyria";
export const aliases = ["flag: Syria","flag_syria","syrian","arab","republic","flag","nation","country","banner","syria"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1f8_1f1fe";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
