// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagStPierreMiquelon
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1f5_1f1f2.png";

export const icon = png;
export const name = "FlagStPierreMiquelon";
export const aliases = ["flag: St. Pierre & Miquelon","flag_st_pierre_miquelon","saint","pierre","miquelon","flag","nation","country","banner","st_pierre_miquelon"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1f5_1f1f2";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
