// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagCeutaMelilla
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1ea_1f1e6.png";

export const icon = png;
export const name = "FlagCeutaMelilla";
export const aliases = ["flag: Ceuta & Melilla","flag_ceuta_melilla"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1ea_1f1e6";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
