// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagAlgeria
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1e9_1f1ff.png";

export const icon = png;
export const name = "FlagAlgeria";
export const aliases = ["flag: Algeria","flag_algeria","dz","flag","nation","country","banner","algeria"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1e9_1f1ff";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
