// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagIceland
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1ee_1f1f8.png";

export const icon = png;
export const name = "FlagIceland";
export const aliases = ["flag: Iceland","flag_iceland","is","flag","nation","country","banner","iceland"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1ee_1f1f8";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
