// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagGreece
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1ec.png";

export const icon = png;
export const name = "FlagGreece";
export const aliases = ["flag_greece","gr","flag","nation","country","banner","greece"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1ec";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
