// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagCostaRica
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1e8_1f1f7.png";

export const icon = png;
export const name = "FlagCostaRica";
export const aliases = ["flag: Costa Rica","flag_costa_rica","costa","rica","flag","nation","country","banner","costa_rica"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1e8_1f1f7";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
