// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagMonaco
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f1f2_1f1e8.png";

export const icon = png;
export const name = "FlagMonaco";
export const aliases = ["flag: Monaco","flag_monaco","mc","flag","nation","country","banner","monaco"];
export const width = 160;
export const height = 160;
export const unicode = "u1f1f2_1f1e8";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
