// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ForkAndKnifeWithPlate
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f37d.png";

export const icon = png;
export const name = "ForkAndKnifeWithPlate";
export const aliases = ["fork_and_knife_with_plate","food","eat","meal","lunch","dinner","restaurant"];
export const width = 160;
export const height = 160;
export const unicode = "u1f37d";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
