// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Fox
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f98a.png";

export const icon = png;
export const name = "Fox";
export const aliases = ["fox","animal","nature","face"];
export const width = 160;
export const height = 160;
export const unicode = "u1f98a";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
