// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Foggy
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f301.png";

export const icon = png;
export const name = "Foggy";
export const aliases = ["foggy","foggy","photo","mountain"];
export const width = 160;
export const height = 160;
export const unicode = "u1f301";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
