// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FREEButton
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f193.png";

export const icon = png;
export const name = "FREEButton";
export const aliases = ["FREE button","free_button","blue-square","words"];
export const width = 160;
export const height = 160;
export const unicode = "u1f193";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
