// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FriedShrimp
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f364.png";

export const icon = png;
export const name = "FriedShrimp";
export const aliases = ["fried_shrimp","food","animal","appetizer","summer"];
export const width = 160;
export const height = 160;
export const unicode = "u1f364";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
