// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FrontFacingBabyChick
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f425.png";

export const icon = png;
export const name = "FrontFacingBabyChick";
export const aliases = ["front-facing baby chick","front_facing_baby_chick","animal","chicken","baby","bird"];
export const width = 160;
export const height = 160;
export const unicode = "u1f425";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
