// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FrowningFaceWithOpenMouth
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f626.png";

export const icon = png;
export const name = "FrowningFaceWithOpenMouth";
export const aliases = ["frowning_face_with_open_mouth","face","aw","what"];
export const width = 160;
export const height = 160;
export const unicode = "u1f626";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
