// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Ghost
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f47b.png";

export const icon = png;
export const name = "Ghost";
export const aliases = ["ghost","ghost","halloween","spooky","scary"];
export const width = 160;
export const height = 160;
export const unicode = "u1f47b";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
