// This file is auto-generated by script/buildTypes.ts
// Emoji definition for GlassOfMilk
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f95b.png";

export const icon = png;
export const name = "GlassOfMilk";
export const aliases = ["glass_of_milk","beverage","drink","cow"];
export const width = 160;
export const height = 160;
export const unicode = "u1f95b";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
