// This file is auto-generated by script/buildTypes.ts
// Emoji definition for GoalNet
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f945.png";

export const icon = png;
export const name = "GoalNet";
export const aliases = ["goal_net","sports"];
export const width = 160;
export const height = 160;
export const unicode = "u1f945";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
