// This file is auto-generated by script/buildTypes.ts
// Emoji definition for GreenBook
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f4d7.png";

export const icon = png;
export const name = "GreenBook";
export const aliases = ["green_book","read","library","knowledge","study"];
export const width = 160;
export const height = 160;
export const unicode = "u1f4d7";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
