// This file is auto-generated by script/buildTypes.ts
// Emoji definition for GrinningFace
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f600.png";

export const icon = png;
export const name = "GrinningFace";
export const aliases = ["grinning face","grinning_face","face","smile","happy","joy",":D","grin"];
export const width = 160;
export const height = 160;
export const unicode = "u1f600";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
