// This file is auto-generated by script/buildTypes.ts
// Emoji definition for GrinningCat
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f63a.png";

export const icon = png;
export const name = "GrinningCat";
export const aliases = ["grinning_cat","animal","cats","happy","smile"];
export const width = 160;
export const height = 160;
export const unicode = "u1f63a";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
