// This file is auto-generated by script/buildTypes.ts
// Emoji definition for GrowingHeart
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f497.png";

export const icon = png;
export const name = "GrowingHeart";
export const aliases = ["growing_heart","like","love","affection","valentines","pink"];
export const width = 160;
export const height = 160;
export const unicode = "u1f497";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
