// This file is auto-generated by script/buildTypes.ts
// Emoji definition for GrimacingFace
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f62c.png";

export const icon = png;
export const name = "GrimacingFace";
export const aliases = ["grimacing_face","face","grimace","teeth"];
export const width = 160;
export const height = 160;
export const unicode = "u1f62c";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
