// This file is auto-generated by script/buildTypes.ts
// Emoji definition for HammerAndPick
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u2692.png";

export const icon = png;
export const name = "HammerAndPick";
export const aliases = ["hammer and pick"];
export const width = 160;
export const height = 160;
export const unicode = "u2692";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
