// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Hamburger
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f354.png";

export const icon = png;
export const name = "Hamburger";
export const aliases = ["hamburger","hamburger","meat","fast food","beef","cheeseburger","mcdonalds","burger king"];
export const width = 160;
export const height = 160;
export const unicode = "u1f354";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
