// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Handshake
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f91d.png";

export const icon = png;
export const name = "Handshake";
export const aliases = ["handshake","handshake","agreement","shake"];
export const width = 160;
export const height = 160;
export const unicode = "u1f91d";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
