// This file is auto-generated by script/buildTypes.ts
// Emoji definition for HearNoEvilMonkey
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f649.png";

export const icon = png;
export const name = "HearNoEvilMonkey";
export const aliases = ["hear_no_evil_monkey","animal","monkey","nature"];
export const width = 160;
export const height = 160;
export const unicode = "u1f649";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
