// This file is auto-generated by script/buildTypes.ts
// Emoji definition for HeartWithRibbon
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f49d.png";

export const icon = png;
export const name = "HeartWithRibbon";
export const aliases = ["heart with ribbon","heart_with_ribbon","love","valentines"];
export const width = 160;
export const height = 160;
export const unicode = "u1f49d";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
