// This file is auto-generated by script/buildTypes.ts
// Emoji definition for HeartDecoration
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f49f.png";

export const icon = png;
export const name = "HeartDecoration";
export const aliases = ["heart_decoration","purple-square","love","like"];
export const width = 160;
export const height = 160;
export const unicode = "u1f49f";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
