// This file is auto-generated by script/buildTypes.ts
// Emoji definition for HeadShakingVertically
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f642_200d_2195_fe0f.png";

export const icon = png;
export const name = "HeadShakingVertically";
export const aliases = ["head shaking vertically"];
export const width = 160;
export const height = 160;
export const unicode = "u1f642_200d_2195_fe0f";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
