// This file is auto-generated by script/buildTypes.ts
// Emoji definition for HeartHandsLightSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1faf6_1f3fb.png";

export const icon = png;
export const name = "HeartHandsLightSkinTone";
export const aliases = ["heart hands: light skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1faf6_1f3fb";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
