// This file is auto-generated by script/buildTypes.ts
// Emoji definition for HeartHands
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1faf6.png";

export const icon = png;
export const name = "HeartHands";
export const aliases = ["heart hands","love","appreciation","support"];
export const width = 160;
export const height = 160;
export const unicode = "u1faf6";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
