// This file is auto-generated by script/buildTypes.ts
// Emoji definition for HeartExclamation
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u2763.png";

export const icon = png;
export const name = "HeartExclamation";
export const aliases = ["heart_exclamation","decoration","love"];
export const width = 160;
export const height = 160;
export const unicode = "u2763";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
