// This file is auto-generated by script/buildTypes.ts
// Emoji definition for HikingBoot
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f97e.png";

export const icon = png;
export const name = "HikingBoot";
export const aliases = ["hiking_boot","backpacking","camping","hiking"];
export const width = 160;
export const height = 160;
export const unicode = "u1f97e";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
