// This file is auto-generated by script/buildTypes.ts
// Emoji definition for HouseWithGarden
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f3e1.png";

export const icon = png;
export const name = "HouseWithGarden";
export const aliases = ["house_with_garden","home","plant","nature"];
export const width = 160;
export const height = 160;
export const unicode = "u1f3e1";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
