// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Horse
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f40e.png";

export const icon = png;
export const name = "Horse";
export const aliases = ["horse","animal","gamble","luck"];
export const width = 160;
export const height = 160;
export const unicode = "u1f40e";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
