// This file is auto-generated by script/buildTypes.ts
// Emoji definition for IndexPointingAtTheViewerMediumDarkSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1faf5_1f3fe.png";

export const icon = png;
export const name = "IndexPointingAtTheViewerMediumDarkSkinTone";
export const aliases = ["index pointing at the viewer: medium-dark skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1faf5_1f3fe";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
