// This file is auto-generated by script/buildTypes.ts
// Emoji definition for IndexPointingUp
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u261d.png";

export const icon = png;
export const name = "IndexPointingUp";
export const aliases = ["index pointing up"];
export const width = 160;
export const height = 160;
export const unicode = "u261d";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
