// This file is auto-generated by script/buildTypes.ts
// Emoji definition for IncomingEnvelope
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f4e8.png";

export const icon = png;
export const name = "IncomingEnvelope";
export const aliases = ["incoming_envelope","email","inbox"];
export const width = 160;
export const height = 160;
export const unicode = "u1f4e8";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
