// This file is auto-generated by script/buildTypes.ts
// Emoji definition for InputLatinUppercase
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f520.png";

export const icon = png;
export const name = "InputLatinUppercase";
export const aliases = ["input latin uppercase","input_latin_uppercase","alphabet","words","blue-square"];
export const width = 160;
export const height = 160;
export const unicode = "u1f520";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
