// This file is auto-generated by script/buildTypes.ts
// Emoji definition for JapaneseNoVacancyButton
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f235.png";

export const icon = png;
export const name = "JapaneseNoVacancyButton";
export const aliases = ["japanese_no_vacancy_button","full","chinese","japanese","red-square","kanji"];
export const width = 160;
export const height = 160;
export const unicode = "u1f235";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
