// This file is auto-generated by script/buildTypes.ts
// Emoji definition for JapaneseApplicationButton
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f238.png";

export const icon = png;
export const name = "JapaneseApplicationButton";
export const aliases = ["Japanese “application” button","japanese_application_button","chinese","japanese","kanji","orange-square"];
export const width = 160;
export const height = 160;
export const unicode = "u1f238";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
