// This file is auto-generated by script/buildTypes.ts
// Emoji definition for JapanesePostOffice
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f3e3.png";

export const icon = png;
export const name = "JapanesePostOffice";
export const aliases = ["Japanese post office","japanese_post_office","building","envelope","communication"];
export const width = 160;
export const height = 160;
export const unicode = "u1f3e3";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
