// This file is auto-generated by script/buildTypes.ts
// Emoji definition for JapaneseCongratulationsButton
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u3297.png";

export const icon = png;
export const name = "JapaneseCongratulationsButton";
export const aliases = ["japanese_congratulations_button","chinese","kanji","japanese","red-circle"];
export const width = 160;
export const height = 160;
export const unicode = "u3297";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
