// This file is auto-generated by script/buildTypes.ts
// Emoji definition for JapaneseServiceChargeButton
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f202.png";

export const icon = png;
export const name = "JapaneseServiceChargeButton";
export const aliases = ["Japanese “service charge” button"];
export const width = 160;
export const height = 160;
export const unicode = "u1f202";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
