// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Kangaroo
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f998.png";

export const icon = png;
export const name = "Kangaroo";
export const aliases = ["kangaroo","kangaroo","animal","nature","australia","joey","hop","marsupial"];
export const width = 160;
export const height = 160;
export const unicode = "u1f998";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
