// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Keycap8
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u38.png";

export const icon = png;
export const name = "Keycap8";
export const aliases = ["keycap_8","8","blue-square","numbers"];
export const width = 160;
export const height = 160;
export const unicode = "u38";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
