// This file is auto-generated by script/buildTypes.ts
// Emoji definition for KeycapDigitSeven
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u37_fe0f_20e3.png";

export const icon = png;
export const name = "KeycapDigitSeven";
export const aliases = ["keycap: digit seven","keycap_7","7","numbers","blue-square","prime"];
export const width = 160;
export const height = 160;
export const unicode = "u37_fe0f_20e3";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
