// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Keycap3
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u33.png";

export const icon = png;
export const name = "Keycap3";
export const aliases = ["keycap_3","3","numbers","prime","blue-square"];
export const width = 160;
export const height = 160;
export const unicode = "u33";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
