// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Keyboard
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u2328.png";

export const icon = png;
export const name = "Keyboard";
export const aliases = ["keyboard","technology","computer","type","input","text"];
export const width = 160;
export const height = 160;
export const unicode = "u2328";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
