// This file is auto-generated by script/buildTypes.ts
// Emoji definition for KeycapDigitFive
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u35_fe0f_20e3.png";

export const icon = png;
export const name = "KeycapDigitFive";
export const aliases = ["keycap: digit five","keycap_5","5","numbers","blue-square","prime"];
export const width = 160;
export const height = 160;
export const unicode = "u35_fe0f_20e3";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
