// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Keycap2
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u2a.png";

export const icon = png;
export const name = "Keycap2";
export const aliases = ["keycap_","star","keycap"];
export const width = 160;
export const height = 160;
export const unicode = "u2a";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
