// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Keycap
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u23.png";

export const icon = png;
export const name = "Keycap";
export const aliases = ["keycap_","symbol","blue-square","twitter"];
export const width = 160;
export const height = 160;
export const unicode = "u23";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
