// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Keycap10
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f51f.png";

export const icon = png;
export const name = "Keycap10";
export const aliases = ["keycap_10","numbers","10","blue-square"];
export const width = 160;
export const height = 160;
export const unicode = "u1f51f";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
