// This file is auto-generated by script/buildTypes.ts
// Emoji definition for KissPersonPersonMediumDarkSkinToneMediumSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f9d1_1f3fe_200d_2764_fe0f_200d_1f48b_200d_1f9d1_1f3fd.png";

export const icon = png;
export const name = "KissPersonPersonMediumDarkSkinToneMediumSkinTone";
export const aliases = ["kiss: person, person, medium-dark skin tone, medium skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1f9d1_1f3fe_200d_2764_fe0f_200d_1f48b_200d_1f9d1_1f3fd";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
