// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Kimono
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f458.png";

export const icon = png;
export const name = "Kimono";
export const aliases = ["kimono","dress","fashion","women","female","japanese"];
export const width = 160;
export const height = 160;
export const unicode = "u1f458";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
