// This file is auto-generated by script/buildTypes.ts
// Emoji definition for KissWomanWoman
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f469.png";

export const icon = png;
export const name = "KissWomanWoman";
export const aliases = ["kiss_woman_woman","pair","valentines","love","like","dating","marriage"];
export const width = 160;
export const height = 160;
export const unicode = "u1f469";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
