// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Laptop
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f4bb.png";

export const icon = png;
export const name = "Laptop";
export const aliases = ["laptop","laptop","technology","laptop","screen","display","monitor"];
export const width = 160;
export const height = 160;
export const unicode = "u1f4bb";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
