// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Leo
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u264c.png";

export const icon = png;
export const name = "Leo";
export const aliases = ["leo","sign","purple-square","zodiac","astrology"];
export const width = 160;
export const height = 160;
export const unicode = "u264c";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
