// This file is auto-generated by script/buildTypes.ts
// Emoji definition for LeftSpeechBubble
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f5e8.png";

export const icon = png;
export const name = "LeftSpeechBubble";
export const aliases = ["left speech bubble"];
export const width = 160;
export const height = 160;
export const unicode = "u1f5e8";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
