// This file is auto-generated by script/buildTypes.ts
// Emoji definition for LeftRightArrow
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u2194.png";

export const icon = png;
export const name = "LeftRightArrow";
export const aliases = ["left_right_arrow","shape","direction","horizontal","sideways"];
export const width = 160;
export const height = 160;
export const unicode = "u2194";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
