// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Leopard
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f406.png";

export const icon = png;
export const name = "Leopard";
export const aliases = ["leopard","leopard","animal","nature"];
export const width = 160;
export const height = 160;
export const unicode = "u1f406";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
