// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Link
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f517.png";

export const icon = png;
export const name = "Link";
export const aliases = ["link","rings","url"];
export const width = 160;
export const height = 160;
export const unicode = "u1f517";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
