// This file is auto-generated by script/buildTypes.ts
// Emoji definition for LinkedPaperclips
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f587.png";

export const icon = png;
export const name = "LinkedPaperclips";
export const aliases = ["linked paperclips"];
export const width = 160;
export const height = 160;
export const unicode = "u1f587";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
