// This file is auto-generated by script/buildTypes.ts
// Emoji definition for LockedWithPen
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f50f.png";

export const icon = png;
export const name = "LockedWithPen";
export const aliases = ["locked_with_pen","security","secret"];
export const width = 160;
export const height = 160;
export const unicode = "u1f50f";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
