// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Lollipop
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f36d.png";

export const icon = png;
export const name = "Lollipop";
export const aliases = ["lollipop","food","snack","candy","sweet"];
export const width = 160;
export const height = 160;
export const unicode = "u1f36d";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
