// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Lobster
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f99e.png";

export const icon = png;
export const name = "Lobster";
export const aliases = ["lobster","lobster","animal","nature","bisque","claws","seafood"];
export const width = 160;
export const height = 160;
export const unicode = "u1f99e";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
