// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ManGettingHaircutMediumDarkSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f487_1f3fe_200d_2642_fe0f.png";

export const icon = png;
export const name = "ManGettingHaircutMediumDarkSkinTone";
export const aliases = ["man getting haircut: medium-dark skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1f487_1f3fe_200d_2642_fe0f";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
