// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ManMechanicMediumDarkSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f468_1f3fe_200d_1f527.png";

export const icon = png;
export const name = "ManMechanicMediumDarkSkinTone";
export const aliases = ["man mechanic: medium-dark skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1f468_1f3fe_200d_1f527";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
