// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ManLightSkinToneWhiteHair
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f468_1f3fb_200d_1f9b3.png";

export const icon = png;
export const name = "ManLightSkinToneWhiteHair";
export const aliases = ["man: light skin tone, white hair"];
export const width = 160;
export const height = 160;
export const unicode = "u1f468_1f3fb_200d_1f9b3";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
