// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ManMage
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f9d9.png";

export const icon = png;
export const name = "ManMage";
export const aliases = ["man_mage","man","male","mage","sorcerer"];
export const width = 160;
export const height = 160;
export const unicode = "u1f9d9";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
