// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ManBald
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f468_200d_1f9b2.png";

export const icon = png;
export const name = "ManBald";
export const aliases = ["man: bald","man_bald","hairless"];
export const width = 160;
export const height = 160;
export const unicode = "u1f468_200d_1f9b2";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
