// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ManJudgeMediumSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f468_1f3fd_200d_2696_fe0f.png";

export const icon = png;
export const name = "ManJudgeMediumSkinTone";
export const aliases = ["man judge: medium skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1f468_1f3fd_200d_2696_fe0f";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
