// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ManElf
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f9dd.png";

export const icon = png;
export const name = "ManElf";
export const aliases = ["man_elf","man","male"];
export const width = 160;
export const height = 160;
export const unicode = "u1f9dd";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
