// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ManFarmerMediumLightSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f468_1f3fc_200d_1f33e.png";

export const icon = png;
export const name = "ManFarmerMediumLightSkinTone";
export const aliases = ["man farmer: medium-light skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1f468_1f3fc_200d_1f33e";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
