// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ManBowing
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f647.png";

export const icon = png;
export const name = "ManBowing";
export const aliases = ["man_bowing","man","male","boy"];
export const width = 160;
export const height = 160;
export const unicode = "u1f647";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
