// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ManInLotusPositionMediumSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f9d8_1f3fd_200d_2642_fe0f.png";

export const icon = png;
export const name = "ManInLotusPositionMediumSkinTone";
export const aliases = ["man in lotus position: medium skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1f9d8_1f3fd_200d_2642_fe0f";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
