// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ManSingerLightSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f468_1f3fb_200d_1f3a4.png";

export const icon = png;
export const name = "ManSingerLightSkinTone";
export const aliases = ["man singer: light skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1f468_1f3fb_200d_1f3a4";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
