// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ManHealthWorker
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f468_200d_2695_fe0f.png";

export const icon = png;
export const name = "ManHealthWorker";
export const aliases = ["man health worker","man_health_worker","doctor","nurse","therapist","healthcare","man","human"];
export const width = 160;
export const height = 160;
export const unicode = "u1f468_200d_2695_fe0f";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
