// This file is auto-generated by script/buildTypes.ts
// Emoji definition for MantelpieceClock
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f570.png";

export const icon = png;
export const name = "MantelpieceClock";
export const aliases = ["mantelpiece_clock","time"];
export const width = 160;
export const height = 160;
export const unicode = "u1f570";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
