// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ManArtistMediumSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f468_1f3fd_200d_1f3a8.png";

export const icon = png;
export const name = "ManArtistMediumSkinTone";
export const aliases = ["man artist: medium skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1f468_1f3fd_200d_1f3a8";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
