// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ManRedHair
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f468_200d_1f9b0.png";

export const icon = png;
export const name = "ManRedHair";
export const aliases = ["man: red hair","man_red_hair","hairstyle"];
export const width = 160;
export const height = 160;
export const unicode = "u1f468_200d_1f9b0";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
