// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ManGenie
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f9de_200d_2642_fe0f.png";

export const icon = png;
export const name = "ManGenie";
export const aliases = ["man genie","man_genie","man","male"];
export const width = 160;
export const height = 160;
export const unicode = "u1f9de_200d_2642_fe0f";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
