// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ManShrugging
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f937_200d_2642_fe0f.png";

export const icon = png;
export const name = "ManShrugging";
export const aliases = ["man shrugging","man_shrugging","man","male","boy","confused","indifferent","doubt"];
export const width = 160;
export const height = 160;
export const unicode = "u1f937_200d_2642_fe0f";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
