// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ManWithVeilDarkSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f470_1f3ff_200d_2642_fe0f.png";

export const icon = png;
export const name = "ManWithVeilDarkSkinTone";
export const aliases = ["man with veil: dark skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1f470_1f3ff_200d_2642_fe0f";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
