// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ManInTuxedoMediumDarkSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f935_1f3fe_200d_2642_fe0f.png";

export const icon = png;
export const name = "ManInTuxedoMediumDarkSkinTone";
export const aliases = ["man in tuxedo: medium-dark skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1f935_1f3fe_200d_2642_fe0f";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
