// This file is auto-generated by script/buildTypes.ts
// Emoji definition for MaleSign
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u2642.png";

export const icon = png;
export const name = "MaleSign";
export const aliases = ["male_sign","man","boy","men"];
export const width = 160;
export const height = 160;
export const unicode = "u2642";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
