// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ManBouncingBall
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u26f9_fe0f_200d_2642_fe0f.png";

export const icon = png;
export const name = "ManBouncingBall";
export const aliases = ["man bouncing ball","man_bouncing_ball","sport"];
export const width = 160;
export const height = 160;
export const unicode = "u26f9_fe0f_200d_2642_fe0f";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
