// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ManWithSkullcap
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f472.png";

export const icon = png;
export const name = "ManWithSkullcap";
export const aliases = ["man_with_skullcap","male","boy","chinese"];
export const width = 160;
export const height = 160;
export const unicode = "u1f472";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
