// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ManGettingHaircut
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f487_200d_2642_fe0f.png";

export const icon = png;
export const name = "ManGettingHaircut";
export const aliases = ["man getting haircut","man_getting_haircut","male","boy","man"];
export const width = 160;
export const height = 160;
export const unicode = "u1f487_200d_2642_fe0f";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
