// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ManCartwheeling
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f938.png";

export const icon = png;
export const name = "ManCartwheeling";
export const aliases = ["man_cartwheeling","gymnastics"];
export const width = 160;
export const height = 160;
export const unicode = "u1f938";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
