// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ManClimbingMediumLightSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f9d7_1f3fc_200d_2642_fe0f.png";

export const icon = png;
export const name = "ManClimbingMediumLightSkinTone";
export const aliases = ["man climbing: medium-light skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1f9d7_1f3fc_200d_2642_fe0f";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
