// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ManFactoryWorker
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f468_200d_1f3ed.png";

export const icon = png;
export const name = "ManFactoryWorker";
export const aliases = ["man factory worker","man_factory_worker","assembly","industrial","man","human"];
export const width = 160;
export const height = 160;
export const unicode = "u1f468_200d_1f3ed";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
