// This file is auto-generated by script/buildTypes.ts
// Emoji definition for MendingHeart
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u2764_fe0f_200d_1fa79.png";

export const icon = png;
export const name = "MendingHeart";
export const aliases = ["mending heart","mending heart","broken heart","bandage","wounded"];
export const width = 160;
export const height = 160;
export const unicode = "u2764_fe0f_200d_1fa79";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
