// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Megaphone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f4e3.png";

export const icon = png;
export const name = "Megaphone";
export const aliases = ["megaphone","sound","speaker","volume"];
export const width = 160;
export const height = 160;
export const unicode = "u1f4e3";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
