// This file is auto-generated by script/buildTypes.ts
// Emoji definition for MirrorBall
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1faa9.png";

export const icon = png;
export const name = "MirrorBall";
export const aliases = ["mirror ball","disco","dance","party"];
export const width = 160;
export const height = 160;
export const unicode = "u1faa9";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
