// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Mirror
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1fa9e.png";

export const icon = png;
export const name = "Mirror";
export const aliases = ["mirror","mirror","reflection"];
export const width = 160;
export const height = 160;
export const unicode = "u1fa9e";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
