// This file is auto-generated by script/buildTypes.ts
// Emoji definition for MilitaryHelmet
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1fa96.png";

export const icon = png;
export const name = "MilitaryHelmet";
export const aliases = ["military helmet","military helmet","army","protection"];
export const width = 160;
export const height = 160;
export const unicode = "u1fa96";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
