// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Mountain
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u26f0.png";

export const icon = png;
export const name = "Mountain";
export const aliases = ["mountain"];
export const width = 160;
export const height = 160;
export const unicode = "u26f0";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
