// This file is auto-generated by script/buildTypes.ts
// Emoji definition for MonkeyFace
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f435.png";

export const icon = png;
export const name = "MonkeyFace";
export const aliases = ["monkey_face","animal","nature","circus"];
export const width = 160;
export const height = 160;
export const unicode = "u1f435";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
