// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Motorcycle
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f3cd.png";

export const icon = png;
export const name = "Motorcycle";
export const aliases = ["motorcycle","race","sports","fast"];
export const width = 160;
export const height = 160;
export const unicode = "u1f3cd";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
