// This file is auto-generated by script/buildTypes.ts
// Emoji definition for MutedSpeaker
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f507.png";

export const icon = png;
export const name = "MutedSpeaker";
export const aliases = ["muted speaker","muted_speaker","sound","volume","silence","quiet"];
export const width = 160;
export const height = 160;
export const unicode = "u1f507";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
