// This file is auto-generated by script/buildTypes.ts
// Emoji definition for MxClausMediumSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f9d1_1f3fd_200d_1f384.png";

export const icon = png;
export const name = "MxClausMediumSkinTone";
export const aliases = ["mx claus: medium skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1f9d1_1f3fd_200d_1f384";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
