// This file is auto-generated by script/buildTypes.ts
// Emoji definition for NazarAmulet
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f9ff.png";

export const icon = png;
export const name = "NazarAmulet";
export const aliases = ["nazar_amulet","bead","charm"];
export const width = 160;
export const height = 160;
export const unicode = "u1f9ff";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
