// This file is auto-generated by script/buildTypes.ts
// Emoji definition for NextTrackButton
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u23ed.png";

export const icon = png;
export const name = "NextTrackButton";
export const aliases = ["next_track_button","forward","next","blue-square"];
export const width = 160;
export const height = 160;
export const unicode = "u23ed";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
