// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Ninja
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f977.png";

export const icon = png;
export const name = "Ninja";
export const aliases = ["ninja","ninjutsu","skills","japanese"];
export const width = 160;
export const height = 160;
export const unicode = "u1f977";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
