// This file is auto-generated by script/buildTypes.ts
// Emoji definition for NoBicycles
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f6b3.png";

export const icon = png;
export const name = "NoBicycles";
export const aliases = ["no_bicycles","cyclist","prohibited","circle"];
export const width = 160;
export const height = 160;
export const unicode = "u1f6b3";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
