// This file is auto-generated by script/buildTypes.ts
// Emoji definition for NoPedestrians
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f6b7.png";

export const icon = png;
export const name = "NoPedestrians";
export const aliases = ["no pedestrians","no_pedestrians","rules","crossing","walking","circle"];
export const width = 160;
export const height = 160;
export const unicode = "u1f6b7";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
