// This file is auto-generated by script/buildTypes.ts
// Emoji definition for OButton
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f17e.png";

export const icon = png;
export const name = "OButton";
export const aliases = ["o_button","alphabet","red-square","letter"];
export const width = 160;
export const height = 160;
export const unicode = "u1f17e";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
