// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Oden
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f362.png";

export const icon = png;
export const name = "Oden";
export const aliases = ["oden","oden","food","japanese"];
export const width = 160;
export const height = 160;
export const unicode = "u1f362";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
