// This file is auto-generated by script/buildTypes.ts
// Emoji definition for OKHand
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f44c.png";

export const icon = png;
export const name = "OKHand";
export const aliases = ["OK hand","ok_hand","fingers","limbs","perfect","ok","okay"];
export const width = 160;
export const height = 160;
export const unicode = "u1f44c";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
