// This file is auto-generated by script/buildTypes.ts
// Emoji definition for OldKey
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f5dd.png";

export const icon = png;
export const name = "OldKey";
export const aliases = ["old_key","lock","door","password"];
export const width = 160;
export const height = 160;
export const unicode = "u1f5dd";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
