// This file is auto-generated by script/buildTypes.ts
// Emoji definition for OlderPerson
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f9d3.png";

export const icon = png;
export const name = "OlderPerson";
export const aliases = ["older_person","human","elder","senior","gender-neutral"];
export const width = 160;
export const height = 160;
export const unicode = "u1f9d3";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
