// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ONArrow
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f51b.png";

export const icon = png;
export const name = "ONArrow";
export const aliases = ["ON! arrow","on_arrow","arrow","words"];
export const width = 160;
export const height = 160;
export const unicode = "u1f51b";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
