// This file is auto-generated by script/buildTypes.ts
// Emoji definition for OpenBook
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f4d6.png";

export const icon = png;
export const name = "OpenBook";
export const aliases = ["open book","open_book","book","read","library","knowledge","literature","learn","study"];
export const width = 160;
export const height = 160;
export const unicode = "u1f4d6";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
