// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Ophiuchus
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u26ce.png";

export const icon = png;
export const name = "Ophiuchus";
export const aliases = ["ophiuchus","sign","purple-square","constellation","astrology"];
export const width = 160;
export const height = 160;
export const unicode = "u26ce";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
