// This file is auto-generated by script/buildTypes.ts
// Emoji definition for OrangeHeart
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f9e1.png";

export const icon = png;
export const name = "OrangeHeart";
export const aliases = ["orange heart","orange_heart","love","like","affection","valentines"];
export const width = 160;
export const height = 160;
export const unicode = "u1f9e1";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
