// This file is auto-generated by script/buildTypes.ts
// Emoji definition for OrangeCircle
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f7e0.png";

export const icon = png;
export const name = "OrangeCircle";
export const aliases = ["orange circle","orange_circle","round"];
export const width = 160;
export const height = 160;
export const unicode = "u1f7e0";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
