// This file is auto-generated by script/buildTypes.ts
// Emoji definition for PalmUpHand
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1faf4.png";

export const icon = png;
export const name = "PalmUpHand";
export const aliases = ["palm up hand","lift","offer","demand"];
export const width = 160;
export const height = 160;
export const unicode = "u1faf4";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
