// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Parrot
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f99c.png";

export const icon = png;
export const name = "Parrot";
export const aliases = ["parrot","parrot","animal","nature","bird","pirate","talk"];
export const width = 160;
export const height = 160;
export const unicode = "u1f99c";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
