// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Pancakes
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f95e.png";

export const icon = png;
export const name = "Pancakes";
export const aliases = ["pancakes","pancakes","food","breakfast","flapjacks","hotcakes","brunch"];
export const width = 160;
export const height = 160;
export const unicode = "u1f95e";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
