// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Parachute
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1fa82.png";

export const icon = png;
export const name = "Parachute";
export const aliases = ["parachute","fly","glide"];
export const width = 160;
export const height = 160;
export const unicode = "u1fa82";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
