// This file is auto-generated by script/buildTypes.ts
// Emoji definition for PalmsUpTogetherLightSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f932_1f3fb.png";

export const icon = png;
export const name = "PalmsUpTogetherLightSkinTone";
export const aliases = ["palms up together: light skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1f932_1f3fb";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
