// This file is auto-generated by script/buildTypes.ts
// Emoji definition for PButton
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f17f.png";

export const icon = png;
export const name = "PButton";
export const aliases = ["P button"];
export const width = 160;
export const height = 160;
export const unicode = "u1f17f";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
