// This file is auto-generated by script/buildTypes.ts
// Emoji definition for PersonRaisingHandLightSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f64b_1f3fb.png";

export const icon = png;
export const name = "PersonRaisingHandLightSkinTone";
export const aliases = ["person raising hand: light skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1f64b_1f3fb";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
