// This file is auto-generated by script/buildTypes.ts
// Emoji definition for PersonMediumDarkSkinToneCurlyHair
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f9d1_1f3fe_200d_1f9b1.png";

export const icon = png;
export const name = "PersonMediumDarkSkinToneCurlyHair";
export const aliases = ["person: medium-dark skin tone, curly hair"];
export const width = 160;
export const height = 160;
export const unicode = "u1f9d1_1f3fe_200d_1f9b1";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
