// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Peach
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f351.png";

export const icon = png;
export const name = "Peach";
export const aliases = ["peach","peach","fruit","nature","food"];
export const width = 160;
export const height = 160;
export const unicode = "u1f351";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
