// This file is auto-generated by script/buildTypes.ts
// Emoji definition for PersonFeedingBaby
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f9d1_200d_1f37c.png";

export const icon = png;
export const name = "PersonFeedingBaby";
export const aliases = ["person feeding baby","person feeding baby","birth","food"];
export const width = 160;
export const height = 160;
export const unicode = "u1f9d1_200d_1f37c";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
