// This file is auto-generated by script/buildTypes.ts
// Emoji definition for PersonMediumSkinToneBlondHair
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f471_1f3fd.png";

export const icon = png;
export const name = "PersonMediumSkinToneBlondHair";
export const aliases = ["person: medium skin tone, blond hair"];
export const width = 160;
export const height = 160;
export const unicode = "u1f471_1f3fd";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
