// This file is auto-generated by script/buildTypes.ts
// Emoji definition for PersonWithWhiteCane
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f9d1_200d_1f9af.png";

export const icon = png;
export const name = "PersonWithWhiteCane";
export const aliases = ["person with white cane","person_with_probing_cane","blind"];
export const width = 160;
export const height = 160;
export const unicode = "u1f9d1_200d_1f9af";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
