// This file is auto-generated by script/buildTypes.ts
// Emoji definition for PersonRaisingHand
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f64b.png";

export const icon = png;
export const name = "PersonRaisingHand";
export const aliases = ["person_raising_hand","question"];
export const width = 160;
export const height = 160;
export const unicode = "u1f64b";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
