// This file is auto-generated by script/buildTypes.ts
// Emoji definition for PersonKneelingMediumDarkSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f9ce_1f3fe.png";

export const icon = png;
export const name = "PersonKneelingMediumDarkSkinTone";
export const aliases = ["person kneeling: medium-dark skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1f9ce_1f3fe";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
