// This file is auto-generated by script/buildTypes.ts
// Emoji definition for PersonGolfingDarkSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f3cc_1f3ff.png";

export const icon = png;
export const name = "PersonGolfingDarkSkinTone";
export const aliases = ["person golfing: dark skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1f3cc_1f3ff";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
