// This file is auto-generated by script/buildTypes.ts
// Emoji definition for PeopleHoldingHandsLightSkinToneMediumDarkSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f9d1_1f3fb_200d_1f91d_200d_1f9d1_1f3fe.png";

export const icon = png;
export const name = "PeopleHoldingHandsLightSkinToneMediumDarkSkinTone";
export const aliases = ["people holding hands: light skin tone, medium-dark skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1f9d1_1f3fb_200d_1f91d_200d_1f9d1_1f3fe";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
