// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Person
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f9d1.png";

export const icon = png;
export const name = "Person";
export const aliases = ["person","person","gender-neutral","person"];
export const width = 160;
export const height = 160;
export const unicode = "u1f9d1";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
