// This file is auto-generated by script/buildTypes.ts
// Emoji definition for PersonMediumDarkSkinToneBlondHair
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f471_1f3fe.png";

export const icon = png;
export const name = "PersonMediumDarkSkinToneBlondHair";
export const aliases = ["person: medium-dark skin tone, blond hair"];
export const width = 160;
export const height = 160;
export const unicode = "u1f471_1f3fe";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
