// This file is auto-generated by script/buildTypes.ts
// Emoji definition for PeopleWrestling
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f93c.png";

export const icon = png;
export const name = "PeopleWrestling";
export const aliases = ["people_wrestling","sport"];
export const width = 160;
export const height = 160;
export const unicode = "u1f93c";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
