// This file is auto-generated by script/buildTypes.ts
// Emoji definition for PersonInSuitLevitatingMediumDarkSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f574_1f3fe.png";

export const icon = png;
export const name = "PersonInSuitLevitatingMediumDarkSkinTone";
export const aliases = ["person in suit levitating: medium-dark skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1f574_1f3fe";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
