// This file is auto-generated by script/buildTypes.ts
// Emoji definition for PersonWearingTurban
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f473.png";

export const icon = png;
export const name = "PersonWearingTurban";
export const aliases = ["person_wearing_turban","headdress"];
export const width = 160;
export const height = 160;
export const unicode = "u1f473";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
