// This file is auto-generated by script/buildTypes.ts
// Emoji definition for PersonMediumSkinToneBeard
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f9d4_1f3fd.png";

export const icon = png;
export const name = "PersonMediumSkinToneBeard";
export const aliases = ["person: medium skin tone, beard"];
export const width = 160;
export const height = 160;
export const unicode = "u1f9d4_1f3fd";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
