// This file is auto-generated by script/buildTypes.ts
// Emoji definition for PersonInManualWheelchairMediumLightSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f9d1_1f3fc_200d_1f9bd.png";

export const icon = png;
export const name = "PersonInManualWheelchairMediumLightSkinTone";
export const aliases = ["person in manual wheelchair: medium-light skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1f9d1_1f3fc_200d_1f9bd";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
