// This file is auto-generated by script/buildTypes.ts
// Emoji definition for PeaPod
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1fadb.png";

export const icon = png;
export const name = "PeaPod";
export const aliases = ["pea pod","cozy","green"];
export const width = 160;
export const height = 160;
export const unicode = "u1fadb";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
