// This file is auto-generated by script/buildTypes.ts
// Emoji definition for PeaceSymbol
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u262e.png";

export const icon = png;
export const name = "PeaceSymbol";
export const aliases = ["peace_symbol","hippie"];
export const width = 160;
export const height = 160;
export const unicode = "u262e";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
