// This file is auto-generated by script/buildTypes.ts
// Emoji definition for PersonSwimmingMediumLightSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f3ca_1f3fc.png";

export const icon = png;
export const name = "PersonSwimmingMediumLightSkinTone";
export const aliases = ["person swimming: medium-light skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1f3ca_1f3fc";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
