// This file is auto-generated by script/buildTypes.ts
// Emoji definition for PinkHeart
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1fa77.png";

export const icon = png;
export const name = "PinkHeart";
export const aliases = ["pink heart","valentines"];
export const width = 160;
export const height = 160;
export const unicode = "u1fa77";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
