// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Pig
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f416.png";

export const icon = png;
export const name = "Pig";
export const aliases = ["pig","animal","nature"];
export const width = 160;
export const height = 160;
export const unicode = "u1f416";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
