// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Pick
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u26cf.png";

export const icon = png;
export const name = "Pick";
export const aliases = ["pick"];
export const width = 160;
export const height = 160;
export const unicode = "u26cf";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
