// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Pinata
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1fa85.png";

export const icon = png;
export const name = "Pinata";
export const aliases = ["pinata","pinata","mexico","candy","celebration"];
export const width = 160;
export const height = 160;
export const unicode = "u1fa85";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
