// This file is auto-generated by script/buildTypes.ts
// Emoji definition for PilotMediumSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f9d1_1f3fd_200d_2708_fe0f.png";

export const icon = png;
export const name = "PilotMediumSkinTone";
export const aliases = ["pilot: medium skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1f9d1_1f3fd_200d_2708_fe0f";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
