// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Plunger
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1faa0.png";

export const icon = png;
export const name = "Plunger";
export const aliases = ["plunger","toilet"];
export const width = 160;
export const height = 160;
export const unicode = "u1faa0";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
