// This file is auto-generated by script/buildTypes.ts
// Emoji definition for PoultryLeg
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f357.png";

export const icon = png;
export const name = "PoultryLeg";
export const aliases = ["poultry leg","poultry_leg","food","meat","drumstick","bird","chicken","turkey"];
export const width = 160;
export const height = 160;
export const unicode = "u1f357";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
