// This file is auto-generated by script/buildTypes.ts
// Emoji definition for PottedPlant
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1fab4.png";

export const icon = png;
export const name = "PottedPlant";
export const aliases = ["potted plant","greenery","house"];
export const width = 160;
export const height = 160;
export const unicode = "u1fab4";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
