// This file is auto-generated by script/buildTypes.ts
// Emoji definition for PouringLiquid
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1fad7.png";

export const icon = png;
export const name = "PouringLiquid";
export const aliases = ["pouring liquid","pouring liquid","cup","water"];
export const width = 160;
export const height = 160;
export const unicode = "u1fad7";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
