// This file is auto-generated by script/buildTypes.ts
// Emoji definition for PostOffice
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f3e4.png";

export const icon = png;
export const name = "PostOffice";
export const aliases = ["post office","post_office","building","email"];
export const width = 160;
export const height = 160;
export const unicode = "u1f3e4";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
