// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Popcorn
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f37f.png";

export const icon = png;
export const name = "Popcorn";
export const aliases = ["popcorn","food","movie theater","films","snack","drama"];
export const width = 160;
export const height = 160;
export const unicode = "u1f37f";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
