// This file is auto-generated by script/buildTypes.ts
// Emoji definition for PregnantPerson
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1fac4.png";

export const icon = png;
export const name = "PregnantPerson";
export const aliases = ["pregnant person","pregnant person","baby","belly"];
export const width = 160;
export const height = 160;
export const unicode = "u1fac4";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
