// This file is auto-generated by script/buildTypes.ts
// Emoji definition for PregnantMan
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1fac3.png";

export const icon = png;
export const name = "PregnantMan";
export const aliases = ["pregnant man","baby","belly"];
export const width = 160;
export const height = 160;
export const unicode = "u1fac3";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
