// This file is auto-generated by script/buildTypes.ts
// Emoji definition for PurpleHeart
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f49c.png";

export const icon = png;
export const name = "PurpleHeart";
export const aliases = ["purple_heart","love","like","affection","valentines"];
export const width = 160;
export const height = 160;
export const unicode = "u1f49c";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
