// This file is auto-generated by script/buildTypes.ts
// Emoji definition for RaisedBackOfHand
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f91a.png";

export const icon = png;
export const name = "RaisedBackOfHand";
export const aliases = ["raised_back_of_hand","fingers","raised","backhand"];
export const width = 160;
export const height = 160;
export const unicode = "u1f91a";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
