// This file is auto-generated by script/buildTypes.ts
// Emoji definition for RedPaperLantern
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f3ee.png";

export const icon = png;
export const name = "RedPaperLantern";
export const aliases = ["red_paper_lantern","light","paper","halloween","spooky"];
export const width = 160;
export const height = 160;
export const unicode = "u1f3ee";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
