// This file is auto-generated by script/buildTypes.ts
// Emoji definition for RedSquare
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f7e5.png";

export const icon = png;
export const name = "RedSquare";
export const aliases = ["red square","red_square"];
export const width = 160;
export const height = 160;
export const unicode = "u1f7e5";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
