// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ReminderRibbon
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f397.png";

export const icon = png;
export const name = "ReminderRibbon";
export const aliases = ["reminder ribbon"];
export const width = 160;
export const height = 160;
export const unicode = "u1f397";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
