// This file is auto-generated by script/buildTypes.ts
// Emoji definition for RedHeart
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u2764.png";

export const icon = png;
export const name = "RedHeart";
export const aliases = ["red heart"];
export const width = 160;
export const height = 160;
export const unicode = "u2764";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
