// This file is auto-generated by script/buildTypes.ts
// Emoji definition for RightwardsPushingHand
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1faf8.png";

export const icon = png;
export const name = "RightwardsPushingHand";
export const aliases = ["rightwards pushing hand","highfive","pressing","stop"];
export const width = 160;
export const height = 160;
export const unicode = "u1faf8";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
