// This file is auto-generated by script/buildTypes.ts
// Emoji definition for RightwardsHand
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1faf1.png";

export const icon = png;
export const name = "RightwardsHand";
export const aliases = ["rightwards hand","rightwards hand","palm","offer"];
export const width = 160;
export const height = 160;
export const unicode = "u1faf1";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
