// This file is auto-generated by script/buildTypes.ts
// Emoji definition for RightwardsHandMediumSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1faf1_1f3fd.png";

export const icon = png;
export const name = "RightwardsHandMediumSkinTone";
export const aliases = ["rightwards hand: medium skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1faf1_1f3fd";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
