// This file is auto-generated by script/buildTypes.ts
// Emoji definition for RollOfPaper
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f9fb.png";

export const icon = png;
export const name = "RollOfPaper";
export const aliases = ["roll_of_paper","roll"];
export const width = 160;
export const height = 160;
export const unicode = "u1f9fb";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
