// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Rooster
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f413.png";

export const icon = png;
export const name = "Rooster";
export const aliases = ["rooster","rooster","animal","nature","chicken"];
export const width = 160;
export const height = 160;
export const unicode = "u1f413";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
