// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Rose
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f339.png";

export const icon = png;
export const name = "Rose";
export const aliases = ["rose","rose","flowers","valentines","love","spring"];
export const width = 160;
export const height = 160;
export const unicode = "u1f339";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
