// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Scorpio
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u264f.png";

export const icon = png;
export const name = "Scorpio";
export const aliases = ["scorpio","sign","zodiac","purple-square","astrology","scorpio"];
export const width = 160;
export const height = 160;
export const unicode = "u264f";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
