// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Scorpion
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f982.png";

export const icon = png;
export const name = "Scorpion";
export const aliases = ["scorpion","scorpion","animal","arachnid"];
export const width = 160;
export const height = 160;
export const unicode = "u1f982";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
