// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Scissors
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u2702.png";

export const icon = png;
export const name = "Scissors";
export const aliases = ["scissors"];
export const width = 160;
export const height = 160;
export const unicode = "u2702";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
