// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ServiceDog
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f415_200d_1f9ba.png";

export const icon = png;
export const name = "ServiceDog";
export const aliases = ["service dog","service_dog","blind","animal"];
export const width = 160;
export const height = 160;
export const unicode = "u1f415_200d_1f9ba";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
