// This file is auto-generated by script/buildTypes.ts
// Emoji definition for SevenOClock
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f556.png";

export const icon = png;
export const name = "SevenOClock";
export const aliases = ["seven_o_clock","7","7:00","700","19:00","1900","time","late","early","schedule"];
export const width = 160;
export const height = 160;
export const unicode = "u1f556";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
