// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ShallowPanOfFood
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f958.png";

export const icon = png;
export const name = "ShallowPanOfFood";
export const aliases = ["shallow pan of food","shallow_pan_of_food","food","cooking","casserole","paella","skillet"];
export const width = 160;
export const height = 160;
export const unicode = "u1f958";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
