// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Singer
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f9d1_200d_1f3a4.png";

export const icon = png;
export const name = "Singer";
export const aliases = ["singer","singer","song","artist","performer"];
export const width = 160;
export const height = 160;
export const unicode = "u1f9d1_200d_1f3a4";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
