// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Skier
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u26f7.png";

export const icon = png;
export const name = "Skier";
export const aliases = ["skier","sports","winter","snow"];
export const width = 160;
export const height = 160;
export const unicode = "u26f7";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
