// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Skull
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f480.png";

export const icon = png;
export const name = "Skull";
export const aliases = ["skull","skull","dead","skeleton","creepy","death"];
export const width = 160;
export const height = 160;
export const unicode = "u1f480";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
