// This file is auto-generated by script/buildTypes.ts
// Emoji definition for SlightlyFrowningFace
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f641.png";

export const icon = png;
export const name = "SlightlyFrowningFace";
export const aliases = ["slightly_frowning_face","face","frowning","disappointed","sad","upset"];
export const width = 160;
export const height = 160;
export const unicode = "u1f641";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
