// This file is auto-generated by script/buildTypes.ts
// Emoji definition for SmilingFaceWithSunglasses
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f60e.png";

export const icon = png;
export const name = "SmilingFaceWithSunglasses";
export const aliases = ["smiling_face_with_sunglasses","face","cool","smile","summer","beach","sunglass"];
export const width = 160;
export const height = 160;
export const unicode = "u1f60e";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
