// This file is auto-generated by script/buildTypes.ts
// Emoji definition for SmirkingFace
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f60f.png";

export const icon = png;
export const name = "SmirkingFace";
export const aliases = ["smirking_face","face","smile","mean","prank","smug","sarcasm"];
export const width = 160;
export const height = 160;
export const unicode = "u1f60f";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
