// This file is auto-generated by script/buildTypes.ts
// Emoji definition for SmilingCatWithHeartEyes
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f63b.png";

export const icon = png;
export const name = "SmilingCatWithHeartEyes";
export const aliases = ["smiling cat with heart-eyes","smiling_cat_with_heart_eyes","animal","love","like","affection","cats","valentines","heart"];
export const width = 160;
export const height = 160;
export const unicode = "u1f63b";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
