// This file is auto-generated by script/buildTypes.ts
// Emoji definition for SnowmanWithoutSnow
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u26c4.png";

export const icon = png;
export const name = "SnowmanWithoutSnow";
export const aliases = ["snowman_without_snow","winter","season","cold","weather","christmas","xmas","frozen","without_snow"];
export const width = 160;
export const height = 160;
export const unicode = "u26c4";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
