// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Snowflake
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u2744.png";

export const icon = png;
export const name = "Snowflake";
export const aliases = ["snowflake","winter","season","cold","weather","christmas","xmas"];
export const width = 160;
export const height = 160;
export const unicode = "u2744";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
