// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Snowman
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u2603.png";

export const icon = png;
export const name = "Snowman";
export const aliases = ["snowman"];
export const width = 160;
export const height = 160;
export const unicode = "u2603";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
