// This file is auto-generated by script/buildTypes.ts
// Emoji definition for SOONArrow
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f51c.png";

export const icon = png;
export const name = "SOONArrow";
export const aliases = ["SOON arrow","soon_arrow","arrow","words"];
export const width = 160;
export const height = 160;
export const unicode = "u1f51c";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
