// This file is auto-generated by script/buildTypes.ts
// Emoji definition for SosButton
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f198.png";

export const icon = png;
export const name = "SosButton";
export const aliases = ["sos_button","help","red-square","words","emergency","911"];
export const width = 160;
export const height = 160;
export const unicode = "u1f198";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
