// This file is auto-generated by script/buildTypes.ts
// Emoji definition for SpeechBalloon
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f4ac.png";

export const icon = png;
export const name = "SpeechBalloon";
export const aliases = ["speech balloon","speech_balloon","bubble","words","message","talk","chatting"];
export const width = 160;
export const height = 160;
export const unicode = "u1f4ac";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
