// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Sponge
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f9fd.png";

export const icon = png;
export const name = "Sponge";
export const aliases = ["sponge","sponge","absorbing","cleaning","porous"];
export const width = 160;
export const height = 160;
export const unicode = "u1f9fd";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
