// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Spoon
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f944.png";

export const icon = png;
export const name = "Spoon";
export const aliases = ["spoon","cutlery","kitchen","tableware"];
export const width = 160;
export const height = 160;
export const unicode = "u1f944";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
