// This file is auto-generated by script/buildTypes.ts
// Emoji definition for SpiralNotepad
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f5d2.png";

export const icon = png;
export const name = "SpiralNotepad";
export const aliases = ["spiral_notepad","memo","stationery"];
export const width = 160;
export const height = 160;
export const unicode = "u1f5d2";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
