// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Speedboat
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f6a4.png";

export const icon = png;
export const name = "Speedboat";
export const aliases = ["speedboat","ship","transportation","vehicle","summer"];
export const width = 160;
export const height = 160;
export const unicode = "u1f6a4";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
