// This file is auto-generated by script/buildTypes.ts
// Emoji definition for SquintingFaceWithTongue
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f61d.png";

export const icon = png;
export const name = "SquintingFaceWithTongue";
export const aliases = ["squinting face with tongue","squinting_face_with_tongue","face","prank","playful","mischievous","smile","tongue"];
export const width = 160;
export const height = 160;
export const unicode = "u1f61d";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
