// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Star
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u2b50.png";

export const icon = png;
export const name = "Star";
export const aliases = ["star","night","yellow"];
export const width = 160;
export const height = 160;
export const unicode = "u2b50";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
