// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Station
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f689.png";

export const icon = png;
export const name = "Station";
export const aliases = ["station","transportation","vehicle","public"];
export const width = 160;
export const height = 160;
export const unicode = "u1f689";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
