// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Sunglasses
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f576.png";

export const icon = png;
export const name = "Sunglasses";
export const aliases = ["sunglasses"];
export const width = 160;
export const height = 160;
export const unicode = "u1f576";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
