// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Sunflower
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f33b.png";

export const icon = png;
export const name = "Sunflower";
export const aliases = ["sunflower","sunflower","nature","plant","fall"];
export const width = 160;
export const height = 160;
export const unicode = "u1f33b";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
