// This file is auto-generated by script/buildTypes.ts
// Emoji definition for SunriseOverMountains
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f304.png";

export const icon = png;
export const name = "SunriseOverMountains";
export const aliases = ["sunrise_over_mountains","view","vacation","photo"];
export const width = 160;
export const height = 160;
export const unicode = "u1f304";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
