// This file is auto-generated by script/buildTypes.ts
// Emoji definition for SuperheroMediumDarkSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f9b8_1f3fe.png";

export const icon = png;
export const name = "SuperheroMediumDarkSkinTone";
export const aliases = ["superhero: medium-dark skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1f9b8_1f3fe";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
