// This file is auto-generated by script/buildTypes.ts
// Emoji definition for TanabataTree
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f38b.png";

export const icon = png;
export const name = "TanabataTree";
export const aliases = ["tanabata tree","tanabata_tree","plant","nature","branch","summer","bamboo","wish","star_festival","tanzaku"];
export const width = 160;
export const height = 160;
export const unicode = "u1f38b";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
