// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Taco
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f32e.png";

export const icon = png;
export const name = "Taco";
export const aliases = ["taco","taco","food","mexican"];
export const width = 160;
export const height = 160;
export const unicode = "u1f32e";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
