// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Telephone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u260e.png";

export const icon = png;
export const name = "Telephone";
export const aliases = ["telephone","technology","communication","dial","telephone"];
export const width = 160;
export const height = 160;
export const unicode = "u260e";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
