// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Tornado
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f32a.png";

export const icon = png;
export const name = "Tornado";
export const aliases = ["tornado","weather","cyclone","twister"];
export const width = 160;
export const height = 160;
export const unicode = "u1f32a";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
