// This file is auto-generated by script/buildTypes.ts
// Emoji definition for TokyoTower
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f5fc.png";

export const icon = png;
export const name = "TokyoTower";
export const aliases = ["Tokyo tower","tokyo_tower","photo","japanese"];
export const width = 160;
export const height = 160;
export const unicode = "u1f5fc";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
