// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Tongue
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f445.png";

export const icon = png;
export const name = "Tongue";
export const aliases = ["tongue","mouth","playful"];
export const width = 160;
export const height = 160;
export const unicode = "u1f445";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
