// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Trumpet
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f3ba.png";

export const icon = png;
export const name = "Trumpet";
export const aliases = ["trumpet","music","brass"];
export const width = 160;
export const height = 160;
export const unicode = "u1f3ba";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
