// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Turkey
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f983.png";

export const icon = png;
export const name = "Turkey";
export const aliases = ["turkey","turkey","animal","bird"];
export const width = 160;
export const height = 160;
export const unicode = "u1f983";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
