// This file is auto-generated by script/buildTypes.ts
// Emoji definition for UmbrellaWithRainDrops
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u2614.png";

export const icon = png;
export const name = "UmbrellaWithRainDrops";
export const aliases = ["umbrella_with_rain_drops","rainy","weather","spring"];
export const width = 160;
export const height = 160;
export const unicode = "u2614";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
