// This file is auto-generated by script/buildTypes.ts
// Emoji definition for UpLeftArrow
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u2196.png";

export const icon = png;
export const name = "UpLeftArrow";
export const aliases = ["up-left arrow"];
export const width = 160;
export const height = 160;
export const unicode = "u2196";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
