// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Volcano
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f30b.png";

export const icon = png;
export const name = "Volcano";
export const aliases = ["volcano","photo","nature","disaster"];
export const width = 160;
export const height = 160;
export const unicode = "u1f30b";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
