// This file is auto-generated by script/buildTypes.ts
// Emoji definition for WaningGibbousMoon
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f316.png";

export const icon = png;
export const name = "WaningGibbousMoon";
export const aliases = ["waning_gibbous_moon","nature","twilight","planet","space","night","evening","sleep","waxing_gibbous_moon"];
export const width = 160;
export const height = 160;
export const unicode = "u1f316";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
