// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Watch
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u231a.png";

export const icon = png;
export const name = "Watch";
export const aliases = ["watch","time","accessories"];
export const width = 160;
export const height = 160;
export const unicode = "u231a";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
