// This file is auto-generated by script/buildTypes.ts
// Emoji definition for WavyDash
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u3030.png";

export const icon = png;
export const name = "WavyDash";
export const aliases = ["wavy_dash","draw","line","moustache","mustache","squiggle","scribble"];
export const width = 160;
export const height = 160;
export const unicode = "u3030";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
