// This file is auto-generated by script/buildTypes.ts
// Emoji definition for WhiteCane
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f9af.png";

export const icon = png;
export const name = "WhiteCane";
export const aliases = ["white cane","probing_cane","accessibility"];
export const width = 160;
export const height = 160;
export const unicode = "u1f9af";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
