// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Whale
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f40b.png";

export const icon = png;
export const name = "Whale";
export const aliases = ["whale","whale","animal","nature","sea","ocean"];
export const width = 160;
export const height = 160;
export const unicode = "u1f40b";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
