// This file is auto-generated by script/buildTypes.ts
// Emoji definition for WhiteCircle
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u26aa.png";

export const icon = png;
export const name = "WhiteCircle";
export const aliases = ["white circle","white_circle","shape","round"];
export const width = 160;
export const height = 160;
export const unicode = "u26aa";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
