// This file is auto-generated by script/buildTypes.ts
// Emoji definition for WiltedFlower
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f940.png";

export const icon = png;
export const name = "WiltedFlower";
export const aliases = ["wilted flower","wilted_flower","plant","nature","flower","rose"];
export const width = 160;
export const height = 160;
export const unicode = "u1f940";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
