// This file is auto-generated by script/buildTypes.ts
// Emoji definition for WindChime
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f390.png";

export const icon = png;
export const name = "WindChime";
export const aliases = ["wind chime","wind_chime","nature","ding","spring","bell"];
export const width = 160;
export const height = 160;
export const unicode = "u1f390";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
