// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Wing
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1fabd.png";

export const icon = png;
export const name = "Wing";
export const aliases = ["wing","wing","angel","birds","flying"];
export const width = 160;
export const height = 160;
export const unicode = "u1fabd";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
