// This file is auto-generated by script/buildTypes.ts
// Emoji definition for WomanKneelingMediumDarkSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f9ce_1f3fe_200d_2640_fe0f.png";

export const icon = png;
export const name = "WomanKneelingMediumDarkSkinTone";
export const aliases = ["woman kneeling: medium-dark skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1f9ce_1f3fe_200d_2640_fe0f";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
