// This file is auto-generated by script/buildTypes.ts
// Emoji definition for WomanGettingHaircutLightSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f487_1f3fb_200d_2640_fe0f.png";

export const icon = png;
export const name = "WomanGettingHaircutLightSkinTone";
export const aliases = ["woman getting haircut: light skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1f487_1f3fb_200d_2640_fe0f";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
