// This file is auto-generated by script/buildTypes.ts
// Emoji definition for WomanInSteamyRoomMediumSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f9d6_1f3fd_200d_2640_fe0f.png";

export const icon = png;
export const name = "WomanInSteamyRoomMediumSkinTone";
export const aliases = ["woman in steamy room: medium skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1f9d6_1f3fd_200d_2640_fe0f";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
