// This file is auto-generated by script/buildTypes.ts
// Emoji definition for WomanDancing
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f483.png";

export const icon = png;
export const name = "WomanDancing";
export const aliases = ["woman dancing","woman_dancing","female","girl","woman","fun"];
export const width = 160;
export const height = 160;
export const unicode = "u1f483";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
