// This file is auto-generated by script/buildTypes.ts
// Emoji definition for WomanInManualWheelchairMediumDarkSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f469_1f3fe_200d_1f9bd.png";

export const icon = png;
export const name = "WomanInManualWheelchairMediumDarkSkinTone";
export const aliases = ["woman in manual wheelchair: medium-dark skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1f469_1f3fe_200d_1f9bd";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
