// This file is auto-generated by script/buildTypes.ts
// Emoji definition for WomanAndManHoldingHandsDarkSkinToneMediumLightSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f469_1f3ff_200d_1f91d_200d_1f468_1f3fc.png";

export const icon = png;
export const name = "WomanAndManHoldingHandsDarkSkinToneMediumLightSkinTone";
export const aliases = ["woman and man holding hands: dark skin tone, medium-light skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1f469_1f3ff_200d_1f91d_200d_1f468_1f3fc";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
