// This file is auto-generated by script/buildTypes.ts
// Emoji definition for WomanGenie
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f9de_200d_2640_fe0f.png";

export const icon = png;
export const name = "WomanGenie";
export const aliases = ["woman genie","woman_genie","woman","female"];
export const width = 160;
export const height = 160;
export const unicode = "u1f9de_200d_2640_fe0f";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
