// This file is auto-generated by script/buildTypes.ts
// Emoji definition for WomanFactoryWorker
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f469_200d_1f3ed.png";

export const icon = png;
export const name = "WomanFactoryWorker";
export const aliases = ["woman factory worker","woman_factory_worker","assembly","industrial","woman","human"];
export const width = 160;
export const height = 160;
export const unicode = "u1f469_200d_1f3ed";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
