// This file is auto-generated by script/buildTypes.ts
// Emoji definition for WomanKneeling
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f9ce.png";

export const icon = png;
export const name = "WomanKneeling";
export const aliases = ["woman_kneeling","respectful","pray"];
export const width = 160;
export const height = 160;
export const unicode = "u1f9ce";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
