// This file is auto-generated by script/buildTypes.ts
// Emoji definition for WomanMountainBiking
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f6b5.png";

export const icon = png;
export const name = "WomanMountainBiking";
export const aliases = ["woman_mountain_biking","transportation","sports","human","race","bike","woman","female"];
export const width = 160;
export const height = 160;
export const unicode = "u1f6b5";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
