// This file is auto-generated by script/buildTypes.ts
// Emoji definition for WomanSwimmingDarkSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f3ca_1f3ff_200d_2640_fe0f.png";

export const icon = png;
export const name = "WomanSwimmingDarkSkinTone";
export const aliases = ["woman swimming: dark skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1f3ca_1f3ff_200d_2640_fe0f";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
