// This file is auto-generated by script/buildTypes.ts
// Emoji definition for WomanFairy
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f9da.png";

export const icon = png;
export const name = "WomanFairy";
export const aliases = ["woman_fairy","woman","female"];
export const width = 160;
export const height = 160;
export const unicode = "u1f9da";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
