// This file is auto-generated by script/buildTypes.ts
// Emoji definition for WomenHoldingHandsDarkSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f46d_1f3ff.png";

export const icon = png;
export const name = "WomenHoldingHandsDarkSkinTone";
export const aliases = ["women holding hands: dark skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1f46d_1f3ff";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
