// This file is auto-generated by script/buildTypes.ts
// Emoji definition for WomanCartwheeling
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f938_200d_2640_fe0f.png";

export const icon = png;
export const name = "WomanCartwheeling";
export const aliases = ["woman cartwheeling","woman_cartwheeling","gymnastics"];
export const width = 160;
export const height = 160;
export const unicode = "u1f938_200d_2640_fe0f";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
