// This file is auto-generated by script/buildTypes.ts
// Emoji definition for WomanGettingMassage
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f486.png";

export const icon = png;
export const name = "WomanGettingMassage";
export const aliases = ["woman_getting_massage","female","girl","woman","head"];
export const width = 160;
export const height = 160;
export const unicode = "u1f486";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
