// This file is auto-generated by script/buildTypes.ts
// Emoji definition for WomanSHat
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f452.png";

export const icon = png;
export const name = "WomanSHat";
export const aliases = ["woman’s hat","woman_s_hat","fashion","accessories","female","lady","spring"];
export const width = 160;
export const height = 160;
export const unicode = "u1f452";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
