// This file is auto-generated by script/buildTypes.ts
// Emoji definition for WomanCurlyHair
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f469_200d_1f9b1.png";

export const icon = png;
export const name = "WomanCurlyHair";
export const aliases = ["woman: curly hair","woman_curly_hair","hairstyle"];
export const width = 160;
export const height = 160;
export const unicode = "u1f469_200d_1f9b1";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
