// This file is auto-generated by script/buildTypes.ts
// Emoji definition for WomanRaisingHand
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f64b.png";

export const icon = png;
export const name = "WomanRaisingHand";
export const aliases = ["woman_raising_hand","female","girl","woman"];
export const width = 160;
export const height = 160;
export const unicode = "u1f64b";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
