// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Wood
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1fab5.png";

export const icon = png;
export const name = "Wood";
export const aliases = ["wood","wood","nature","timber","trunk"];
export const width = 160;
export const height = 160;
export const unicode = "u1fab5";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
