// This file is auto-generated by script/buildTypes.ts
// Emoji definition for WomanTeacherMediumLightSkinTone
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f469_1f3fc_200d_1f3eb.png";

export const icon = png;
export const name = "WomanTeacherMediumLightSkinTone";
export const aliases = ["woman teacher: medium-light skin tone"];
export const width = 160;
export const height = 160;
export const unicode = "u1f469_1f3fc_200d_1f3eb";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
