// This file is auto-generated by script/buildTypes.ts
// Emoji definition for WomanPilot
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f469_200d_2708_fe0f.png";

export const icon = png;
export const name = "WomanPilot";
export const aliases = ["woman pilot","woman_pilot","aviator","plane","woman","human"];
export const width = 160;
export const height = 160;
export const unicode = "u1f469_200d_2708_fe0f";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
