// This file is auto-generated by script/buildTypes.ts
// Emoji definition for WomanWalking
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f6b6.png";

export const icon = png;
export const name = "WomanWalking";
export const aliases = ["woman_walking","human","feet","steps","woman","female"];
export const width = 160;
export const height = 160;
export const unicode = "u1f6b6";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
