// This file is auto-generated by script/buildTypes.ts
// Emoji definition for WomanWithVeil
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f470.png";

export const icon = png;
export const name = "WomanWithVeil";
export const aliases = ["woman with veil","wedding","marriage"];
export const width = 160;
export const height = 160;
export const unicode = "u1f470";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
