// This file is auto-generated by script/buildTypes.ts
// Emoji definition for WomanInSteamyRoom
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f9d6.png";

export const icon = png;
export const name = "WomanInSteamyRoom";
export const aliases = ["woman_in_steamy_room","female","woman","spa","steamroom","sauna"];
export const width = 160;
export const height = 160;
export const unicode = "u1f9d6";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
