// This file is auto-generated by script/buildTypes.ts
// Emoji definition for WomanSClothes
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f45a.png";

export const icon = png;
export const name = "WomanSClothes";
export const aliases = ["woman_s_clothes","fashion","shopping_bags","female"];
export const width = 160;
export const height = 160;
export const unicode = "u1f45a";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
