// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Wrench
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f527.png";

export const icon = png;
export const name = "Wrench";
export const aliases = ["wrench","wrench","tools","diy","ikea","fix","maintainer"];
export const width = 160;
export const height = 160;
export const unicode = "u1f527";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
