// This file is auto-generated by script/buildTypes.ts
// Emoji definition for XRay
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1fa7b.png";

export const icon = png;
export const name = "XRay";
export const aliases = ["x-ray","x-ray","skeleton","medicine"];
export const width = 160;
export const height = 160;
export const unicode = "u1fa7b";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
