// This file is auto-generated by script/buildTypes.ts
// Emoji definition for YoYo
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1fa80.png";

export const icon = png;
export const name = "YoYo";
export const aliases = ["yo_yo","toy"];
export const width = 160;
export const height = 160;
export const unicode = "u1fa80";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
