// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ZanyFace
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f92a.png";

export const icon = png;
export const name = "ZanyFace";
export const aliases = ["zany_face","face","goofy","crazy"];
export const width = 160;
export const height = 160;
export const unicode = "u1f92a";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
