// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ZipperMouthFace
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f910.png";

export const icon = png;
export const name = "ZipperMouthFace";
export const aliases = ["zipper_mouth_face","face","sealed","zipper","secret"];
export const width = 160;
export const height = 160;
export const unicode = "u1f910";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
