// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Zombie
import type { AppleIconDefinition } from "../index.js";
import png from "../png/160/emoji_u1f9df.png";

export const icon = png;
export const name = "Zombie";
export const aliases = ["zombie","dead"];
export const width = 160;
export const height = 160;
export const unicode = "u1f9df";

export default {
  icon,
  name,
  aliases,
  width,
  height,
  unicode,
} as AppleIconDefinition;
