// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Alembic
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u2697.webp"),
  name: "Alembic",
  aliases: ["alembic"],
  width: 160,
  height: 160,
  unicode: "u2697",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
