// This file is auto-generated by script/buildTypes.ts
// Emoji definition for AlarmClock
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u23f0.webp"),
  name: "AlarmClock",
  aliases: ["alarm clock","alarm_clock","time","wake"],
  width: 160,
  height: 160,
  unicode: "u23f0",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
