// This file is auto-generated by script/buildTypes.ts
// Emoji definition for AnatomicalHeart
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1fac0.webp"),
  name: "AnatomicalHeart",
  aliases: ["anatomical heart","anatomical heart","health","heartbeat"],
  width: 160,
  height: 160,
  unicode: "u1fac0",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
