// This file is auto-generated by script/buildTypes.ts
// Emoji definition for BeerMug
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f37a.webp"),
  name: "BeerMug",
  aliases: ["beer mug","beer_mug","relax","beverage","drink","drunk","party","pub","summer","alcohol","booze"],
  width: 160,
  height: 160,
  unicode: "u1f37a",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
