// This file is auto-generated by script/buildTypes.ts
// Emoji definition for BellWithSlash
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f515.webp"),
  name: "BellWithSlash",
  aliases: ["bell with slash","bell_with_slash","sound","volume","mute","quiet","silent"],
  width: 160,
  height: 160,
  unicode: "u1f515",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
