// This file is auto-generated by script/buildTypes.ts
// Emoji definition for BlackCat
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f408_200d_2b1b.webp"),
  name: "BlackCat",
  aliases: ["black cat","black cat","superstition","luck"],
  width: 160,
  height: 160,
  unicode: "u1f408_200d_2b1b",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
