// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Briefcase
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f4bc.webp"),
  name: "Briefcase",
  aliases: ["briefcase","briefcase","business","documents","work","law","legal","job","career"],
  width: 160,
  height: 160,
  unicode: "u1f4bc",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
