// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Cancer
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u264b.webp"),
  name: "Cancer",
  aliases: ["Cancer","cancer","sign","zodiac","purple-square","astrology"],
  width: 160,
  height: 160,
  unicode: "u264b",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
