// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Church
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u26ea.webp"),
  name: "Church",
  aliases: ["church","church","building","religion","christ"],
  width: 160,
  height: 160,
  unicode: "u26ea",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
