// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ClosedMailboxWithRaisedFlag
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f4eb.webp"),
  name: "ClosedMailboxWithRaisedFlag",
  aliases: ["closed mailbox with raised flag","closed_mailbox_with_raised_flag","email","inbox","communication"],
  width: 160,
  height: 160,
  unicode: "u1f4eb",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
