// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ClapperBoard
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f3ac.webp"),
  name: "ClapperBoard",
  aliases: ["clapper board","clapper_board","movie","film","record"],
  width: 160,
  height: 160,
  unicode: "u1f3ac",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
