// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Coin
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1fa99.webp"),
  name: "Coin",
  aliases: ["coin","coin","money","currency"],
  width: 160,
  height: 160,
  unicode: "u1fa99",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
