// This file is auto-generated by script/buildTypes.ts
// Emoji definition for CoupleWithHeartWomanWoman
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f469_200d_2764_fe0f_200d_1f469.webp"),
  name: "CoupleWithHeartWomanWoman",
  aliases: ["couple with heart: woman, woman","couple_with_heart_woman_woman","pair","love","like","affection","human","dating","valentines","marriage"],
  width: 160,
  height: 160,
  unicode: "u1f469_200d_2764_fe0f_200d_1f469",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
