// This file is auto-generated by script/buildTypes.ts
// Emoji definition for CoupleWithHeartWomanMan
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f469_200d_2764_fe0f_200d_1f468.webp"),
  name: "CoupleWithHeartWomanMan",
  aliases: ["couple with heart: woman, man","couple_with_heart_woman_man","love"],
  width: 160,
  height: 160,
  unicode: "u1f469_200d_2764_fe0f_200d_1f468",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
