// This file is auto-generated by script/buildTypes.ts
// Emoji definition for CreditCard
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f4b3.webp"),
  name: "CreditCard",
  aliases: ["credit card","credit_card","money","sales","dollar","bill","payment","shopping"],
  width: 160,
  height: 160,
  unicode: "u1f4b3",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
