// This file is auto-generated by script/buildTypes.ts
// Emoji definition for CutOfMeat
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f969.webp"),
  name: "CutOfMeat",
  aliases: ["cut of meat","cut_of_meat","food","cow","meat","cut","chop","lambchop","porkchop"],
  width: 160,
  height: 160,
  unicode: "u1f969",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
