// This file is auto-generated by script/buildTypes.ts
// Emoji definition for CurlyLoop
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u27b0.webp"),
  name: "CurlyLoop",
  aliases: ["curly loop","curly_loop","scribble","draw","shape","squiggle"],
  width: 160,
  height: 160,
  unicode: "u27b0",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
