// This file is auto-generated by script/buildTypes.ts
// Emoji definition for CupWithStraw
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f964.webp"),
  name: "CupWithStraw",
  aliases: ["cup with straw","cup_with_straw","drink","soda"],
  width: 160,
  height: 160,
  unicode: "u1f964",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
