// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Cyclone
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f300.webp"),
  name: "Cyclone",
  aliases: ["cyclone","cyclone","weather","swirl","blue","cloud","vortex","spiral","whirlpool","spin","tornado","hurricane","typhoon"],
  width: 160,
  height: 160,
  unicode: "u1f300",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
