// This file is auto-generated by script/buildTypes.ts
// Emoji definition for DollarBanknote
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f4b5.webp"),
  name: "DollarBanknote",
  aliases: ["dollar banknote","dollar_banknote","money","sales","bill","currency"],
  width: 160,
  height: 160,
  unicode: "u1f4b5",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
