// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ElevenThirty
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f566.webp"),
  name: "ElevenThirty",
  aliases: ["eleven-thirty","eleven_thirty","11:30","1130","23:30","2330","time","late","early","schedule"],
  width: 160,
  height: 160,
  unicode: "u1f566",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
