// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FaceExhaling
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f62e_200d_1f4a8.webp"),
  name: "FaceExhaling",
  aliases: ["face exhaling","face exhaling","relieve","relief","tired","sigh"],
  width: 160,
  height: 160,
  unicode: "u1f62e_200d_1f4a8",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
