// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FamilyManWomanBoyBoy
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f468_200d_1f469_200d_1f466_200d_1f466.webp"),
  name: "FamilyManWomanBoyBoy",
  aliases: ["family: man, woman, boy, boy","family_man_woman_boy_boy","home","parents","people","human","children"],
  width: 160,
  height: 160,
  unicode: "u1f468_200d_1f469_200d_1f466_200d_1f466",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
