// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FastForwardButton
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u23e9.webp"),
  name: "FastForwardButton",
  aliases: ["fast-forward button","fast_forward_button","blue-square","play","speed","continue"],
  width: 160,
  height: 160,
  unicode: "u23e9",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
