// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FamilyManGirlGirl
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f468_200d_1f467_200d_1f467.webp"),
  name: "FamilyManGirlGirl",
  aliases: ["family: man, girl, girl","family_man_girl_girl","home","parent","people","human","children"],
  width: 160,
  height: 160,
  unicode: "u1f468_200d_1f467_200d_1f467",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
