// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FamilyWomanGirlBoy
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f469_200d_1f467_200d_1f466.webp"),
  name: "FamilyWomanGirlBoy",
  aliases: ["family: woman, girl, boy","family_woman_girl_boy","home","parent","people","human","children"],
  width: 160,
  height: 160,
  unicode: "u1f469_200d_1f467_200d_1f466",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
