// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FaceWithTearsOfJoy
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f602.webp"),
  name: "FaceWithTearsOfJoy",
  aliases: ["face with tears of joy","face_with_tears_of_joy","face","cry","tears","weep","happy","happytears","haha"],
  width: 160,
  height: 160,
  unicode: "u1f602",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
