// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Feather
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1fab6.webp"),
  name: "Feather",
  aliases: ["feather","feather","bird","fly"],
  width: 160,
  height: 160,
  unicode: "u1fab6",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
