// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FiveOClock
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f554.webp"),
  name: "FiveOClock",
  aliases: ["five o’clock","five_o_clock","5","5:00","500","17:00","1700","time","late","early","schedule"],
  width: 160,
  height: 160,
  unicode: "u1f554",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
