// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FileCabinet
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f5c4.webp"),
  name: "FileCabinet",
  aliases: ["file cabinet"],
  width: 160,
  height: 160,
  unicode: "u1f5c4",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
