// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagLatvia
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f1f1_1f1fb.webp"),
  name: "FlagLatvia",
  aliases: ["flag: Latvia","flag_latvia","lv","flag","nation","country","banner","latvia"],
  width: 160,
  height: 160,
  unicode: "u1f1f1_1f1fb",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
