// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlyingDisc
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f94f.webp"),
  name: "FlyingDisc",
  aliases: ["flying disc","flying_disc","sports","frisbee","ultimate"],
  width: 160,
  height: 160,
  unicode: "u1f94f",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
