// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Flatbread
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1fad3.webp"),
  name: "Flatbread",
  aliases: ["flatbread","flatbread","flour","food","bakery"],
  width: 160,
  height: 160,
  unicode: "u1fad3",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
