// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagGuadeloupe
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f1ec_1f1f5.webp"),
  name: "FlagGuadeloupe",
  aliases: ["flag: Guadeloupe","flag_guadeloupe","gp","flag","nation","country","banner","guadeloupe"],
  width: 160,
  height: 160,
  unicode: "u1f1ec_1f1f5",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
