// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagCapeVerde
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f1e8_1f1fb.webp"),
  name: "FlagCapeVerde",
  aliases: ["flag: Cape Verde","flag_cape_verde","cabo","verde","flag","nation","country","banner","cape_verde"],
  width: 160,
  height: 160,
  unicode: "u1f1e8_1f1fb",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
