// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagFiji
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f1eb_1f1ef.webp"),
  name: "FlagFiji",
  aliases: ["flag: Fiji","flag_fiji","fj","flag","nation","country","banner","fiji"],
  width: 160,
  height: 160,
  unicode: "u1f1eb_1f1ef",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
