// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagAlbania
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f1e6_1f1f1.webp"),
  name: "FlagAlbania",
  aliases: ["flag: Albania","flag_albania","al","flag","nation","country","banner","albania"],
  width: 160,
  height: 160,
  unicode: "u1f1e6_1f1f1",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
