// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagBahrain
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f1e7_1f1ed.webp"),
  name: "FlagBahrain",
  aliases: ["flag: Bahrain","flag_bahrain","bh","flag","nation","country","banner","bahrain"],
  width: 160,
  height: 160,
  unicode: "u1f1e7_1f1ed",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
