// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagCaribbeanNetherlands
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f1e7_1f1f6.webp"),
  name: "FlagCaribbeanNetherlands",
  aliases: ["flag: Caribbean Netherlands","flag_caribbean_netherlands","bonaire","flag","nation","country","banner","caribbean_netherlands"],
  width: 160,
  height: 160,
  unicode: "u1f1e7_1f1f6",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
