// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagIraq
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f1ee_1f1f6.webp"),
  name: "FlagIraq",
  aliases: ["flag: Iraq","flag_iraq","iq","flag","nation","country","banner","iraq"],
  width: 160,
  height: 160,
  unicode: "u1f1ee_1f1f6",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
