// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagFrenchSouthernTerritories
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f1f9_1f1eb.webp"),
  name: "FlagFrenchSouthernTerritories",
  aliases: ["flag: French Southern Territories","flag_french_southern_territories","french","southern","territories","flag","nation","country","banner","french_southern_territories"],
  width: 160,
  height: 160,
  unicode: "u1f1f9_1f1eb",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
