// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagReunion
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f1f7_1f1ea.webp"),
  name: "FlagReunion",
  aliases: ["flag: Reunion","flag_reunion","réunion","flag","nation","country","banner","reunion"],
  width: 160,
  height: 160,
  unicode: "u1f1f7_1f1ea",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
