// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagYemen
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f1fe_1f1ea.webp"),
  name: "FlagYemen",
  aliases: ["flag: Yemen","flag_yemen","ye","flag","nation","country","banner","yemen"],
  width: 160,
  height: 160,
  unicode: "u1f1fe_1f1ea",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
