// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagMontserrat
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f1f2_1f1f8.webp"),
  name: "FlagMontserrat",
  aliases: ["flag: Montserrat","flag_montserrat","ms","flag","nation","country","banner","montserrat"],
  width: 160,
  height: 160,
  unicode: "u1f1f2_1f1f8",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
