// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FlagBritishVirginIslands
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f1fb_1f1ec.webp"),
  name: "FlagBritishVirginIslands",
  aliases: ["flag: British Virgin Islands","flag_british_virgin_islands","british","virgin","islands","bvi","flag","nation","country","banner","british_virgin_islands"],
  width: 160,
  height: 160,
  unicode: "u1f1fb_1f1ec",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
