// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FoldingHandFan
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1faad.webp"),
  name: "FoldingHandFan",
  aliases: ["folding hand fan","folding hand fan","flamenco","hot"],
  width: 160,
  height: 160,
  unicode: "u1faad",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
