// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Fountain
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u26f2.webp"),
  name: "Fountain",
  aliases: ["fountain","fountain","photo","summer","water","fresh"],
  width: 160,
  height: 160,
  unicode: "u26f2",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
