// This file is auto-generated by script/buildTypes.ts
// Emoji definition for FriedShrimp
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f364.webp"),
  name: "FriedShrimp",
  aliases: ["fried shrimp","fried_shrimp","food","animal","appetizer","summer"],
  width: 160,
  height: 160,
  unicode: "u1f364",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
