// This file is auto-generated by script/buildTypes.ts
// Emoji definition for GlobeShowingAsiaAustralia
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f30f.webp"),
  name: "GlobeShowingAsiaAustralia",
  aliases: ["globe showing Asia-Australia","globe_showing_asia_australia","globe","world","east","international"],
  width: 160,
  height: 160,
  unicode: "u1f30f",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
