// This file is auto-generated by script/buildTypes.ts
// Emoji definition for GrinningCat
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f63a.webp"),
  name: "GrinningCat",
  aliases: ["grinning cat","grinning_cat","animal","cats","happy","smile"],
  width: 160,
  height: 160,
  unicode: "u1f63a",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
