// This file is auto-generated by script/buildTypes.ts
// Emoji definition for GraduationCap
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f393.webp"),
  name: "GraduationCap",
  aliases: ["graduation cap","graduation_cap","school","college","degree","university","graduation","cap","hat","legal","learn","education"],
  width: 160,
  height: 160,
  unicode: "u1f393",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
