// This file is auto-generated by script/buildTypes.ts
// Emoji definition for HealthWorkerDarkSkinTone
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f9d1_1f3ff_200d_2695_fe0f.webp"),
  name: "HealthWorkerDarkSkinTone",
  aliases: ["health worker: dark skin tone"],
  width: 160,
  height: 160,
  unicode: "u1f9d1_1f3ff_200d_2695_fe0f",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
