// This file is auto-generated by script/buildTypes.ts
// Emoji definition for HorseRacing
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f3c7.webp"),
  name: "HorseRacing",
  aliases: ["horse racing","horse_racing","animal","betting","competition","gambling","luck"],
  width: 160,
  height: 160,
  unicode: "u1f3c7",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
