// This file is auto-generated by script/buildTypes.ts
// Emoji definition for IndexPointingAtTheViewerMediumDarkSkinTone
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1faf5_1f3fe.webp"),
  name: "IndexPointingAtTheViewerMediumDarkSkinTone",
  aliases: ["index pointing at the viewer: medium-dark skin tone"],
  width: 160,
  height: 160,
  unicode: "u1faf5_1f3fe",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
