// This file is auto-generated by script/buildTypes.ts
// Emoji definition for JapaneseApplicationButton
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f238.webp"),
  name: "JapaneseApplicationButton",
  aliases: ["Japanese “application” button","japanese_application_button","chinese","japanese","kanji","orange-square"],
  width: 160,
  height: 160,
  unicode: "u1f238",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
