// This file is auto-generated by script/buildTypes.ts
// Emoji definition for JapaneseCongratulationsButton
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u3297.webp"),
  name: "JapaneseCongratulationsButton",
  aliases: ["Japanese “congratulations” button"],
  width: 160,
  height: 160,
  unicode: "u3297",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
