// This file is auto-generated by script/buildTypes.ts
// Emoji definition for JapaneseNoVacancyButton
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f235.webp"),
  name: "JapaneseNoVacancyButton",
  aliases: ["Japanese “no vacancy” button","japanese_no_vacancy_button","full","chinese","japanese","red-square","kanji"],
  width: 160,
  height: 160,
  unicode: "u1f235",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
