// This file is auto-generated by script/buildTypes.ts
// Emoji definition for JapaneseDiscountButton
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f239.webp"),
  name: "JapaneseDiscountButton",
  aliases: ["Japanese “discount” button","japanese_discount_button","cut","divide","chinese","kanji","pink-square"],
  width: 160,
  height: 160,
  unicode: "u1f239",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
