// This file is auto-generated by script/buildTypes.ts
// Emoji definition for KeycapDigitOne
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u31_fe0f_20e3.webp"),
  name: "KeycapDigitOne",
  aliases: ["keycap: digit one","keycap_1","blue-square","numbers","1"],
  width: 160,
  height: 160,
  unicode: "u31_fe0f_20e3",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
