// This file is auto-generated by script/buildTypes.ts
// Emoji definition for KissWomanWomanMediumLightSkinToneMediumDarkSkinTone
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f469_1f3fc_200d_2764_fe0f_200d_1f48b_200d_1f469_1f3fe.webp"),
  name: "KissWomanWomanMediumLightSkinToneMediumDarkSkinTone",
  aliases: ["kiss: woman, woman, medium-light skin tone, medium-dark skin tone"],
  width: 160,
  height: 160,
  unicode: "u1f469_1f3fc_200d_2764_fe0f_200d_1f48b_200d_1f469_1f3fe",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
