// This file is auto-generated by script/buildTypes.ts
// Emoji definition for KissWomanManMediumDarkSkinToneDarkSkinTone
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f469_1f3fe_200d_2764_fe0f_200d_1f48b_200d_1f468_1f3ff.webp"),
  name: "KissWomanManMediumDarkSkinToneDarkSkinTone",
  aliases: ["kiss: woman, man, medium-dark skin tone, dark skin tone"],
  width: 160,
  height: 160,
  unicode: "u1f469_1f3fe_200d_2764_fe0f_200d_1f48b_200d_1f468_1f3ff",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
