// This file is auto-generated by script/buildTypes.ts
// Emoji definition for KissWomanManDarkSkinToneMediumSkinTone
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f469_1f3ff_200d_2764_fe0f_200d_1f48b_200d_1f468_1f3fd.webp"),
  name: "KissWomanManDarkSkinToneMediumSkinTone",
  aliases: ["kiss: woman, man, dark skin tone, medium skin tone"],
  width: 160,
  height: 160,
  unicode: "u1f469_1f3ff_200d_2764_fe0f_200d_1f48b_200d_1f468_1f3fd",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
