// This file is auto-generated by script/buildTypes.ts
// Emoji definition for LeafFlutteringInWind
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f343.webp"),
  name: "LeafFlutteringInWind",
  aliases: ["leaf fluttering in wind","leaf_fluttering_in_wind","nature","plant","tree","vegetable","grass","lawn","spring"],
  width: 160,
  height: 160,
  unicode: "u1f343",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
