// This file is auto-generated by script/buildTypes.ts
// Emoji definition for LoveLetter
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f48c.webp"),
  name: "LoveLetter",
  aliases: ["love letter","love_letter","email","like","affection","envelope","valentines"],
  width: 160,
  height: 160,
  unicode: "u1f48c",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
