// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ManWearingTurban
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f473_200d_2642_fe0f.webp"),
  name: "ManWearingTurban",
  aliases: ["man wearing turban","man_wearing_turban","male","indian","hinduism","arabs"],
  width: 160,
  height: 160,
  unicode: "u1f473_200d_2642_fe0f",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
