// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ManPouting
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f64e_200d_2642_fe0f.webp"),
  name: "ManPouting",
  aliases: ["man pouting","man_pouting","male","boy","man"],
  width: 160,
  height: 160,
  unicode: "u1f64e_200d_2642_fe0f",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
