// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ManGolfingMediumSkinTone
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f3cc_1f3fd_200d_2642_fe0f.webp"),
  name: "ManGolfingMediumSkinTone",
  aliases: ["man golfing: medium skin tone"],
  width: 160,
  height: 160,
  unicode: "u1f3cc_1f3fd_200d_2642_fe0f",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
