// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ManLightSkinToneCurlyHair
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f468_1f3fb_200d_1f9b1.webp"),
  name: "ManLightSkinToneCurlyHair",
  aliases: ["man: light skin tone, curly hair"],
  width: 160,
  height: 160,
  unicode: "u1f468_1f3fb_200d_1f9b1",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
