// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ManWithWhiteCane
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f468_200d_1f9af.webp"),
  name: "ManWithWhiteCane",
  aliases: ["man with white cane","man_with_probing_cane","blind"],
  width: 160,
  height: 160,
  unicode: "u1f468_200d_1f9af",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
