// This file is auto-generated by script/buildTypes.ts
// Emoji definition for MenSRoom
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f6b9.webp"),
  name: "MenSRoom",
  aliases: ["men’s room","men_s_room","toilet","restroom","wc","blue-square","gender","male"],
  width: 160,
  height: 160,
  unicode: "u1f6b9",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
