// This file is auto-generated by script/buildTypes.ts
// Emoji definition for MobilePhoneWithArrow
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f4f2.webp"),
  name: "MobilePhoneWithArrow",
  aliases: ["mobile phone with arrow","mobile_phone_with_arrow","iphone","incoming"],
  width: 160,
  height: 160,
  unicode: "u1f4f2",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
