// This file is auto-generated by script/buildTypes.ts
// Emoji definition for MoneyWithWings
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f4b8.webp"),
  name: "MoneyWithWings",
  aliases: ["money with wings","money_with_wings","dollar","bills","payment","sale"],
  width: 160,
  height: 160,
  unicode: "u1f4b8",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
