// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Mouth
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f444.webp"),
  name: "Mouth",
  aliases: ["mouth","mouth","mouth","kiss"],
  width: 160,
  height: 160,
  unicode: "u1f444",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
