// This file is auto-generated by script/buildTypes.ts
// Emoji definition for MusicalNote
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f3b5.webp"),
  name: "MusicalNote",
  aliases: ["musical note","musical_note","score","tone","sound"],
  width: 160,
  height: 160,
  unicode: "u1f3b5",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
