// This file is auto-generated by script/buildTypes.ts
// Emoji definition for MxClausMediumDarkSkinTone
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f9d1_1f3fe_200d_1f384.webp"),
  name: "MxClausMediumDarkSkinTone",
  aliases: ["mx claus: medium-dark skin tone"],
  width: 160,
  height: 160,
  unicode: "u1f9d1_1f3fe_200d_1f384",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
