// This file is auto-generated by script/buildTypes.ts
// Emoji definition for NextTrackButton
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u23ed.webp"),
  name: "NextTrackButton",
  aliases: ["next track button"],
  width: 160,
  height: 160,
  unicode: "u23ed",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
