// This file is auto-generated by script/buildTypes.ts
// Emoji definition for NineThirty
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f564.webp"),
  name: "NineThirty",
  aliases: ["nine-thirty","nine_thirty","9:30","930","21:30","2130","time","late","early","schedule"],
  width: 160,
  height: 160,
  unicode: "u1f564",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
