// This file is auto-generated by script/buildTypes.ts
// Emoji definition for NoEntry
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u26d4.webp"),
  name: "NoEntry",
  aliases: ["no entry","no_entry","limit","security","privacy","bad","denied","stop","circle"],
  width: 160,
  height: 160,
  unicode: "u26d4",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
