// This file is auto-generated by script/buildTypes.ts
// Emoji definition for OKHand
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f44c.webp"),
  name: "OKHand",
  aliases: ["OK hand","ok_hand","fingers","limbs","perfect","ok","okay"],
  width: 160,
  height: 160,
  unicode: "u1f44c",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
