// This file is auto-generated by script/buildTypes.ts
// Emoji definition for OrangeHeart
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f9e1.webp"),
  name: "OrangeHeart",
  aliases: ["orange heart","orange_heart","love","like","affection","valentines"],
  width: 160,
  height: 160,
  unicode: "u1f9e1",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
