// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Pager
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f4df.webp"),
  name: "Pager",
  aliases: ["pager","pager","bbcall","oldschool","90s"],
  width: 160,
  height: 160,
  unicode: "u1f4df",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
