// This file is auto-generated by script/buildTypes.ts
// Emoji definition for PeopleHoldingHands
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f9d1_200d_1f91d_200d_1f9d1.webp"),
  name: "PeopleHoldingHands",
  aliases: ["people holding hands","people_holding_hands","friendship"],
  width: 160,
  height: 160,
  unicode: "u1f9d1_200d_1f91d_200d_1f9d1",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
