// This file is auto-generated by script/buildTypes.ts
// Emoji definition for PersonMediumSkinToneRedHair
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f9d1_1f3fd_200d_1f9b0.webp"),
  name: "PersonMediumSkinToneRedHair",
  aliases: ["person: medium skin tone, red hair"],
  width: 160,
  height: 160,
  unicode: "u1f9d1_1f3fd_200d_1f9b0",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
