// This file is auto-generated by script/buildTypes.ts
// Emoji definition for PlaceOfWorship
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f6d0.webp"),
  name: "PlaceOfWorship",
  aliases: ["place of worship","place_of_worship","religion","church","temple","prayer"],
  width: 160,
  height: 160,
  unicode: "u1f6d0",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
