// This file is auto-generated by script/buildTypes.ts
// Emoji definition for PoliceCarLight
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f6a8.webp"),
  name: "PoliceCarLight",
  aliases: ["police car light","police_car_light","police","ambulance","911","emergency","alert","error","pinged","law","legal"],
  width: 160,
  height: 160,
  unicode: "u1f6a8",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
