// This file is auto-generated by script/buildTypes.ts
// Emoji definition for PoliceCar
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f693.webp"),
  name: "PoliceCar",
  aliases: ["police car","police_car","vehicle","cars","transportation","law","legal","enforcement"],
  width: 160,
  height: 160,
  unicode: "u1f693",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
