// This file is auto-generated by script/buildTypes.ts
// Emoji definition for RaisedHandLightSkinTone
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u270b_1f3fb.webp"),
  name: "RaisedHandLightSkinTone",
  aliases: ["raised hand: light skin tone"],
  width: 160,
  height: 160,
  unicode: "u270b_1f3fb",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
