// This file is auto-generated by script/buildTypes.ts
// Emoji definition for RaisedFistMediumLightSkinTone
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u270a_1f3fc.webp"),
  name: "RaisedFistMediumLightSkinTone",
  aliases: ["raised fist: medium-light skin tone"],
  width: 160,
  height: 160,
  unicode: "u270a_1f3fc",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
