// This file is auto-generated by script/buildTypes.ts
// Emoji definition for RepeatSingleButton
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f502.webp"),
  name: "RepeatSingleButton",
  aliases: ["repeat single button","repeat_single_button","blue-square","loop"],
  width: 160,
  height: 160,
  unicode: "u1f502",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
