// This file is auto-generated by script/buildTypes.ts
// Emoji definition for RoastedSweetPotato
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f360.webp"),
  name: "RoastedSweetPotato",
  aliases: ["roasted sweet potato","roasted_sweet_potato","food","nature","plant"],
  width: 160,
  height: 160,
  unicode: "u1f360",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
