// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ShakingFace
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1fae8.webp"),
  name: "ShakingFace",
  aliases: ["shaking face","shaking face","dizzy","shock","blurry","earthquake"],
  width: 160,
  height: 160,
  unicode: "u1fae8",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
