// This file is auto-generated by script/buildTypes.ts
// Emoji definition for ShootingStar
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f320.webp"),
  name: "ShootingStar",
  aliases: ["shooting star","shooting_star","night","photo"],
  width: 160,
  height: 160,
  unicode: "u1f320",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
