// This file is auto-generated by script/buildTypes.ts
// Emoji definition for SixOClock
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f555.webp"),
  name: "SixOClock",
  aliases: ["six o’clock","six_o_clock","6","6:00","600","18:00","1800","time","late","early","schedule","dawn","dusk"],
  width: 160,
  height: 160,
  unicode: "u1f555",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
