// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Singer
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f9d1_200d_1f3a4.webp"),
  name: "Singer",
  aliases: ["singer","singer","song","artist","performer"],
  width: 160,
  height: 160,
  unicode: "u1f9d1_200d_1f3a4",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
