// This file is auto-generated by script/buildTypes.ts
// Emoji definition for SlightlyFrowningFace
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f641.webp"),
  name: "SlightlyFrowningFace",
  aliases: ["slightly frowning face","slightly_frowning_face","face","frowning","disappointed","sad","upset"],
  width: 160,
  height: 160,
  unicode: "u1f641",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
