// This file is auto-generated by script/buildTypes.ts
// Emoji definition for SmilingFaceWithSmilingEyes
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f60a.webp"),
  name: "SmilingFaceWithSmilingEyes",
  aliases: ["smiling face with smiling eyes","smiling_face_with_smiling_eyes","face","smile","happy","flushed","crush","embarrassed","shy","joy"],
  width: 160,
  height: 160,
  unicode: "u1f60a",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
