// This file is auto-generated by script/buildTypes.ts
// Emoji definition for SmirkingFace
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f60f.webp"),
  name: "SmirkingFace",
  aliases: ["smirking face","smirking_face","face","smile","mean","prank","smug","sarcasm"],
  width: 160,
  height: 160,
  unicode: "u1f60f",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
