// This file is auto-generated by script/buildTypes.ts
// Emoji definition for SneezingFace
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f927.webp"),
  name: "SneezingFace",
  aliases: ["sneezing face","sneezing_face","face","gesundheit","sneeze","sick","allergy"],
  width: 160,
  height: 160,
  unicode: "u1f927",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
