// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Socks
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f9e6.webp"),
  name: "Socks",
  aliases: ["socks","socks","stockings","clothes"],
  width: 160,
  height: 160,
  unicode: "u1f9e6",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
