// This file is auto-generated by script/buildTypes.ts
// Emoji definition for SoccerBall
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u26bd.webp"),
  name: "SoccerBall",
  aliases: ["soccer ball","soccer_ball","sports","football"],
  width: 160,
  height: 160,
  unicode: "u26bd",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
