// This file is auto-generated by script/buildTypes.ts
// Emoji definition for TenThirty
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f565.webp"),
  name: "TenThirty",
  aliases: ["ten-thirty","ten_thirty","10:30","1030","22:30","2230","time","late","early","schedule"],
  width: 160,
  height: 160,
  unicode: "u1f565",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
