// This file is auto-generated by script/buildTypes.ts
// Emoji definition for TenOClock
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f559.webp"),
  name: "TenOClock",
  aliases: ["ten o’clock","ten_o_clock","10","10:00","1000","22:00","2200","time","late","early","schedule"],
  width: 160,
  height: 160,
  unicode: "u1f559",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
