// This file is auto-generated by script/buildTypes.ts
// Emoji definition for TeddyBear
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f9f8.webp"),
  name: "TeddyBear",
  aliases: ["teddy bear","teddy_bear","plush","stuffed"],
  width: 160,
  height: 160,
  unicode: "u1f9f8",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
