// This file is auto-generated by script/buildTypes.ts
// Emoji definition for Trophy
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f3c6.webp"),
  name: "Trophy",
  aliases: ["trophy","trophy","win","award","contest","place","ftw","ceremony"],
  width: 160,
  height: 160,
  unicode: "u1f3c6",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
