// This file is auto-generated by script/buildTypes.ts
// Emoji definition for TwoOClock
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f551.webp"),
  name: "TwoOClock",
  aliases: ["two o’clock","two_o_clock","2","2:00","200","14:00","1400","time","late","early","schedule"],
  width: 160,
  height: 160,
  unicode: "u1f551",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
