// This file is auto-generated by script/buildTypes.ts
// Emoji definition for TwoHearts
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f495.webp"),
  name: "TwoHearts",
  aliases: ["two hearts","two_hearts","love","like","affection","valentines","heart"],
  width: 160,
  height: 160,
  unicode: "u1f495",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
