// This file is auto-generated by script/buildTypes.ts
// Emoji definition for TwelveThirty
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f567.webp"),
  name: "TwelveThirty",
  aliases: ["twelve-thirty","twelve_thirty","00:30","0030","12:30","1230","time","late","early","schedule"],
  width: 160,
  height: 160,
  unicode: "u1f567",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
