// This file is auto-generated by script/buildTypes.ts
// Emoji definition for TwelveOClock
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f55b.webp"),
  name: "TwelveOClock",
  aliases: ["twelve o’clock","twelve_o_clock","12","00:00","0000","12:00","1200","time","noon","midnight","midday","late","early","schedule"],
  width: 160,
  height: 160,
  unicode: "u1f55b",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
