// This file is auto-generated by script/buildTypes.ts
// Emoji definition for UnamusedFace
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f612.webp"),
  name: "UnamusedFace",
  aliases: ["unamused face","unamused_face","indifference","bored","straight face","serious","sarcasm","unimpressed","skeptical","dubious","side_eye"],
  width: 160,
  height: 160,
  unicode: "u1f612",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
