// This file is auto-generated by script/buildTypes.ts
// Emoji definition for WhiteLargeSquare
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u2b1c.webp"),
  name: "WhiteLargeSquare",
  aliases: ["white large square","white_large_square","shape","icon","stone","button"],
  width: 160,
  height: 160,
  unicode: "u2b1c",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
