// This file is auto-generated by script/buildTypes.ts
// Emoji definition for WinkingFaceWithTongue
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f61c.webp"),
  name: "WinkingFaceWithTongue",
  aliases: ["winking face with tongue","winking_face_with_tongue","face","prank","childish","playful","mischievous","smile","wink","tongue"],
  width: 160,
  height: 160,
  unicode: "u1f61c",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
