// This file is auto-generated by script/buildTypes.ts
// Emoji definition for WomanInLotusPositionLightSkinTone
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f9d8_1f3fb_200d_2640_fe0f.webp"),
  name: "WomanInLotusPositionLightSkinTone",
  aliases: ["woman in lotus position: light skin tone"],
  width: 160,
  height: 160,
  unicode: "u1f9d8_1f3fb_200d_2640_fe0f",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
