// This file is auto-generated by script/buildTypes.ts
// Emoji definition for WomanGesturingNO
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f645_200d_2640_fe0f.webp"),
  name: "WomanGesturingNO",
  aliases: ["woman gesturing NO","woman_gesturing_no","female","girl","woman","nope"],
  width: 160,
  height: 160,
  unicode: "u1f645_200d_2640_fe0f",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
