// This file is auto-generated by script/buildTypes.ts
// Emoji definition for WomanGesturingOK
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f646_200d_2640_fe0f.webp"),
  name: "WomanGesturingOK",
  aliases: ["woman gesturing OK","woman_gesturing_ok","women","girl","female","pink","human","woman"],
  width: 160,
  height: 160,
  unicode: "u1f646_200d_2640_fe0f",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
