// This file is auto-generated by script/buildTypes.ts
// Emoji definition for WomanCurlyHair
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f469_200d_1f9b1.webp"),
  name: "WomanCurlyHair",
  aliases: ["woman: curly hair","woman_curly_hair","hairstyle"],
  width: 160,
  height: 160,
  unicode: "u1f469_200d_1f9b1",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
