// This file is auto-generated by script/buildTypes.ts
// Emoji definition for WomanMediumLightSkinToneBald
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f469_1f3fc_200d_1f9b2.webp"),
  name: "WomanMediumLightSkinToneBald",
  aliases: ["woman: medium-light skin tone, bald"],
  width: 160,
  height: 160,
  unicode: "u1f469_1f3fc_200d_1f9b2",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
