// This file is auto-generated by script/buildTypes.ts
// Emoji definition for YenBanknote
import type { AppleIconDefinition } from "../index.js";

const definition = {
  icon: import("../webp/emoji_u1f4b4.webp"),
  name: "YenBanknote",
  aliases: ["yen banknote","yen_banknote","money","sales","japanese","dollar","currency"],
  width: 160,
  height: 160,
  unicode: "u1f4b4",
} as AppleIconDefinition;

export const icon = definition.icon;
export const name = definition.name;
export const aliases = definition.aliases;
export const width = definition.width;
export const height = definition.height;
export const unicode = definition.unicode;

export default definition;
